#!/bin/bash
#-----------------------------------------------------------------------------#
# eFa 4.0.0 DMARC TLD Weekly Update Cron
#-----------------------------------------------------------------------------#
# Copyright (C) 2013~2018 https://efa-project.org
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#-----------------------------------------------------------------------------#

# TODO
# 600 sec random backoff
# Host on efa-project.org servers

#Stop OpenDMARC Service
systemctl stop opendmarc

#Remove old tld names file
rm -rf /etc/opendmarc/effective_tld_names.dat


#Get latest effective_tld_names for OpenDMARC
/usr/bin/wget -q -N -P /etc/opendmarc https://publicsuffix.org/list/effective_tld_names.dat

#Start OpenDMARC Server
systemctl start opendmarc