#!/bin/bash
#-----------------------------------------------------------------------------#
# eFa 4.0.0 post initial configuration script
#-----------------------------------------------------------------------------#
# Copyright (C) 2013~2018 https://efa-project.org
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#-----------------------------------------------------------------------------#

############################## PRECHECK #######################################
# Things that must be done before initializing
###############################################################################

# Don't run if reboot is pending
[[ -f /reboot.system ]] && exit 0

# Don't run if lock is present
[[ -f /var/run/eFa-Post-Init.lock ]] && exit 0

# Reset footer
sed -i "/^    echo ' running on ' . efa_version()/ c\    echo ' running on ' . efa_version() . ' ...INITIALIZING SYSTEM, PLEASE WAIT... ';" /var/www/html/mailscanner/functions.php

# Remove eFaInit config if present
[[ -f /etc/httpd/conf.d/eFaInit.conf ]] && rm -f /etc/httpd/conf.d/eFaInit.conf

# Do we have Internet access?
wget -q --tries=3 --timeout=20 --spider https://mirrors.efa-project.org
if [[ $? -ne 0 ]]; then
  logger -p user.warn "eFa Post Init: No Internet access detected!  Please fix me to finish initializing eFa.  Retrying in 1 minute..."
  sed -i "/^    echo ' running on ' . efa_version()/ c\    echo ' running on ' . efa_version() . ' ...ERROR INITIALIZATING, CHECK INTERNET ACCESS... ';" /var/www/html/mailscanner/functions.php
  exit 1
fi

# Precheck passes, create lock file
touch /var/run/eFa-Post-Init.lock

############################## EARLY PHASE ###################################
# Tasks that must happen before allowing email to relay
##############################################################################

# Early daemon restart
systemctl restart sqlgrey
if [[ $? -ne 0 ]]; then
  # Error!  Try again...
  logger -p user.warn "eFa Post Init: sqlgrey restart failed!  Please fix me to finish initializing eFa.  Retrying in 1 minute..."
  sed -i "/^    echo ' running on ' . efa_version()/ c\    echo ' running on ' . efa_version() . ' ...ERROR INITIALIZATING, CHECK SQLGREY... ';" /var/www/html/mailscanner/functions.php
  rm -f /var/run/eFa-Post-Init.lock
  exit 1
fi

# Early asynchronous tasks
/etc/cron.daily/mailscanner &

/usr/bin/mailwatch/tools/Cron_jobs/mailwatch_geoip_update.php &

/usr/sbin/clamav-unofficial-sigs.sh &

# Early synchronous tasks

/usr/bin/mailwatch/tools/Cron_jobs/mailwatch_update_sarules.php

freshclam

systemctl restart clamd@scan
if [[ $? -ne 0 ]]; then
  # Error!  Try again...
  logger -p user.warn "eFa Post Init: Clamd restart failed!  Please fix me to finish initializing eFa.  Retrying in 1 minute..."
  sed -i "/^    echo ' running on ' . efa_version()/ c\    echo ' running on ' . efa_version() . ' ...ERROR INITIALIZATING, CHECK CLAMD... ';" /var/www/html/mailscanner/functions.php
  rm -f /var/run/eFa-Post-Init.lock
  exit 1
fi

# Spawn mta relay stats watchers
/etc/cron.hourly/mailwatch_relay.sh

systemctl enable msmilter
systemctl start msmilter

# Schedule eFa-Monitor cron
echo "* * * * * root /usr/sbin/eFa-Monitor-cron >/dev/null 2>&1" > /etc/cron.d/eFa-Monitor.cron

# Remove INITIALIZING message
sed -i "/^    echo ' running on ' . efa_version()/ c\    echo ' running on ' . efa_version();" /var/www/html/mailscanner/functions.php

############################## LATE PHASE ###################################
# Tasks that are not needed for email to relay
#############################################################################

# Late Asynchronous tasks
/usr/bin/sa-learn --spam /usr/share/doc/spamassassin-3.4.2/sample-spam.txt &
/usr/bin/sa-learn --ham /usr/share/doc/spamassassin-3.4.2/sample-nonspam.txt &

# Late Synchronous tasks
if [[ ! -f /etc/postfix/ssl/dhparam.pem ]]; then
  openssl dhparam -out /etc/postfix/ssl/dhparam.pem 2048
  postconf -e "smtpd_tls_dh1024_param_file = /etc/postfix/ssl/dhparam.pem"
  cat /etc/postfix/ssl/dhparam.pem >> /etc/pki/tls/certs/localhost.crt
fi
  
# Late Reload daemons
systemctl reload postfix
if [[ $? -ne 0 ]]; then
  # Postfix error!
  logger -p user.warn "eFa Post Init: Postfix reload failed!  Please fix me to finish initializing eFa."
fi
systemctl reload httpd
if [[ $? -ne 0 ]]; then
  # Apache Error!
  logger -p user.warn "eFa Post Init: Apache reload failed!  Please fix me to finish initializing eFa."
fi

rm -f /etc/cron.d/efapostinit
rm -f /var/run/eFa-Post-Init.lock
