#!/bin/bash
# +--------------------------------------------------------------------+
# EFA-Configure
# Version 20171004
# +--------------------------------------------------------------------+
# Copyright (C) 2012~2018  https://www.efa-project.org
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
# +--------------------------------------------------------------------+

# +---------------------------------------------------+
# Enable Extended Globs
# +---------------------------------------------------+
shopt -s extglob
# +---------------------------------------------------+

# +---------------------------------------------------+
# Load functions
# +---------------------------------------------------+
. /var/EFA/lib/EFA-Configure/func_getipsettings
. /var/EFA/lib/EFA-Configure/func_sethostname
. /var/EFA/lib/EFA-Configure/func_apachesettings
. /var/EFA/lib/EFA-Configure/func_mailsettings
. /var/EFA/lib/EFA-Configure/func_systemrestore
. /var/EFA/lib/EFA-Configure/func_recovermariadb
. /var/EFA/lib/EFA-Configure/func_spamsettings
. /var/EFA/lib/EFA-Configure/func_trustednetworks
. /var/EFA/lib/EFA-Configure/func_virussettings
. /var/EFA/lib/EFA-Configure/func_askcleandeliver
. /var/EFA/lib/EFA-Configure/func_asksigrules
. /var/EFA/lib/EFA-Configure/func_asknonspam
. /var/EFA/lib/EFA-Configure/func_askspam
. /var/EFA/lib/EFA-Configure/func_ipsettings
. /var/EFA/lib/EFA-Configure/func_greylisting
. /var/EFA/lib/EFA-Configure/func_autoupdates
. /var/EFA/lib/EFA-Configure/func_tunables
. /var/EFA/lib/EFA-Configure/func_tunables_children
. /var/EFA/lib/EFA-Configure/func_tunables_procdb
. /var/EFA/lib/EFA-Configure/func_setipsettings
. /var/EFA/lib/EFA-Configure/func_askmaxsize
. /var/EFA/lib/EFA-Configure/func_mailwatchsettings
. /var/EFA/lib/EFA-Configure/func_resetadmin
. /var/EFA/lib/EFA-Configure/func_askmaxsizemailwatch
. /var/EFA/lib/EFA-Configure/func_askhighspammailwatch
. /var/EFA/lib/EFA-Configure/func_askmalwarepatrol
. /var/EFA/lib/EFA-Configure/func_askrecursion
. /var/EFA/lib/EFA-Configure/func_retention
. /var/EFA/lib/EFA-Configure/func_maintenance
. /var/EFA/lib/EFA-Configure/func_peruser
. /var/EFA/lib/EFA-Configure/func_letsencrypt
. /var/EFA/lib/EFA-Configure/func_askdccservers
. /var/EFA/lib/EFA-Configure/func_dkim_dmarc

# +---------------------------------------------------+

# +---------------------------------------------------+
# Get version
# +---------------------------------------------------+
eFaVERSION="`head /etc/EFA-Version`"
# +---------------------------------------------------+



# +---------------------------------------------------+
# Display menus
# +---------------------------------------------------+
show_menu() {
  menu=1
  while [ $menu == "1" ]
    do
      func_echo-header
      echo -e ""
      echo -e "You are currently running $green$eFaVERSION$clean."
      echo -e ""
      echo -e "Please choose an option:"
      echo -e " "
      echo -e "0) Logout from ssh                    9)  Spam Settings"
      echo -e "1) Shell                              10) MariaDB Recovery"
      echo -e "2) Reboot system                      11) Apache Settings"
      echo -e "3) Halt system                        12) Virus Settings"
      echo -e "4) IP Settings                        13) System Restore"
      echo -e "5) Tunables                           14) Update Now"
      echo -e "6) MailWatch Settings                 15) Maintenance Mode"
      echo -e "7) Auto Update                        16) Let's Encrypt"
      echo -e "8) Mail Settings                      17) DKIM and DMARC"
      echo -e ""
      echo -e -n "$green[eFa]$clean : "
      local choice
      read choice
      case $choice in
                    0) clear; SSHTTY=`/usr/bin/tty |awk -F '/' '{print $3"/"$4}'`; SSHPID=`ps aux | egrep "sshd: [a-zA-Z]+@" | grep -w $SSHTTY | awk '{print $2}'`; kill $SSHPID ;;
                    1) exit 0 ;;
                    2) func_reboot ;;
                    3) func_halt ;;
                    4) func_ip-settings ;;
                    5) func_tunables ;;
                    6) func_mailwatch-settings ;;
                    7) func_autoupdates ;;
                    8) func_mail-settings ;;
                    9) func_spam-settings ;;
                   10) func_recover-mariadb ;;
                   11) func_apache-settings ;;
                   12) func_virus-settings ;;
                   13) func_system-restore ;;
                   14) func_update-now ;;
                   15) func_maintenance-mode ;;
                   16) func_lets-encrypt ;;
                   17) func_dkim-dmarc ;;
                    *) echo -e "Error \"$choice\" is not an option..." && sleep 2
      esac
    done
}
# +---------------------------------------------------+

# +---------------------------------------------------+
# Reboot function
# +---------------------------------------------------+
func_reboot() {
  menu=0
  rebootmenu=1
  while [ $rebootmenu == "1" ]
    do
      func_echo-header
      echo -e "Are you sure you want to reboot this host?"
      echo -e ""
      echo -e "Y)  Yes I am sure"
      echo -e "N)  No no no take me back!"
      echo -e ""
      echo -e -n "$green[eFa]$clean : "
      local choice
      read choice
      case $choice in
                    Y) reboot && exit 0 ;;
                    N) menu=1 && return  ;;
                    n) menu=1 && return  ;;
                    *) echo -e "Error \"$choice\" is not an option..." && sleep 2
      esac
    done
}
# +---------------------------------------------------+

# +---------------------------------------------------+
# Halt function
# +---------------------------------------------------+
func_halt() {
  menu=0
  haltmenu=1
  while [ $haltmenu == "1" ]
    do
      func_echo-header
      echo -e "Are you sure you want to halt this host?"
      echo -e ""
      echo -e "Y)  Yes I am sure"
      echo -e "N)  No no no take me back!"
      echo -e ""
      echo -e -n "$green[eFa]$clean : "
      local choice
      read choice
      case $choice in
                    Y) shutdown -h now && exit 0 ;;
                    N) menu=1 && return  ;;
                    n) menu=1 && return  ;;
                    *) echo -e "Error \"$choice\" is not an option..." && sleep 2
      esac
    done
}
# +---------------------------------------------------+

# +---------------------------------------------------+
# Update Now function
# +---------------------------------------------------+
func_update-now() {
  echo ""
  local yesno
  read -p "Update now, are you sure? (y/N): " yesno
  if [[ $yesno =~ ^[Yy] ]]; then
    /usr/local/sbin/EFA-Update -update
  fi
  pause
}
# +---------------------------------------------------+

# +---------------------------------------------------+
# Function to test IP addresses
# +---------------------------------------------------+
function checkip(){
  local ip=$1
  local stat=1

  if [[ $ip =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
        OIFS=$IFS
        IFS='.'
        ip=($ip)
        IFS=$OIFS
        [[ ${ip[0]} -le 255 && ${ip[1]} -le 255 && ${ip[2]} -le 255 && ${ip[3]} -le 255 ]]
        stat=$?
  fi
  return $stat
}
# +---------------------------------------------------+

# +---------------------------------------------------+
# Trap CTRL+C, CTRL+Z and quit singles
# +---------------------------------------------------+
trap '' SIGINT SIGQUIT SIGTSTP
# +---------------------------------------------------+

# +---------------------------------------------------+
# Pause
# +---------------------------------------------------+
pause(){
  read -p "Press [Enter] key to continue..." fackEnterKey
}
# +---------------------------------------------------+

# +---------------------------------------------------+
# Menu header
# +---------------------------------------------------+
func_echo-header(){
  clear
  echo -e "--------------------------------------------------------------"
  echo -e "---        Welcome to the EFA Configuration program        ---"
  echo -e "---               https://www.efa-project.org              ---"
  echo -e "--------------------------------------------------------------"
  echo ""
}
# +---------------------------------------------------+

# +---------------------------------------------------+
# Main logic
# +---------------------------------------------------+
clear
red='\E[00;31m'
green='\E[00;32m'
yellow='\E[00;33m'
blue='\E[00;34m'
magenta='\E[00;35'
cyan='\E[00;36m'
clean='\e[00m'

if [ `whoami` == root ]
    then
        menu="1"
        while [ $menu == "1" ]
        do
            show_menu
        done
    else
        echo -e "$red [eFa] ERROR: Please become root.$clean"
        exit 0
    fi
# +---------------------------------------------------+
