#!/bin/bash
#-----------------------------------------------------------------------------#
# eFa 4.0.0 post initial configuration script
#-----------------------------------------------------------------------------#
# Copyright (C) 2013~2018 https://efa-project.org
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#-----------------------------------------------------------------------------#

# Don't run if reboot is pending
[[ -f /reboot.system ]] && exit 0

# Don't run if lock is present
[[ -f /var/run/eFa-Post-Init.lock ]] && exit 0

touch /var/run/eFa-Post-Init.lock

# Remove eFaInit config
rm -f /etc/httpd/conf.d/eFaInit.conf

openssl dhparam -out /etc/postfix/ssl/dhparam.pem 2048
postconf -e "smtpd_tls_dh1024_param_file = /etc/postfix/ssl/dhparam.pem"
cat /etc/postfix/ssl/dhparam.pem >> /etc/pki/tls/certs/localhost.crt

sa-update
sa-compile

freshclam

# Update clamav unofficial-sigs
/usr/sbin/clamav-unofficial-sigs.sh

/etc/cron.daily/mailscanner

# Reload daemons
systemctl reload postfix
systemctl reload httpd
systemctl restart clamd@scan
systemctl restart sqlgrey
systemctl enable msmilter
systemctl start msmilter

# Schedule eFa-Monitor cron
echo "* * * * * root /usr/sbin/eFa-Monitor-cron >/dev/null 2>&1" > /etc/cron.d/eFa-Monitor.cron

# Remove INITIALIZING message
sed -i "/^    echo ' running on '/ c\    echo ' running on ' . efa_version();" /var/www/html/mailscanner/functions.php

rm -f /etc/cron.d/efapostinit
rm -f /var/run/eFa-Post-Init.lock
