
package Mail::SpamAssassin::CompiledRegexps::body_0;

use strict;

use XSLoader ();

BEGIN {
our $VERSION = '1.0';
our @ISA = qw(XSLoader);
our @EXPORT_OK = qw();

our $HAS_RULES = {
    q#ACT_NOW_CAPS,[l=1]# => q#/\bA(?i:ct) N(?i:ow)\b/#,
  q#BAD_CREDIT,[l=1]# => q#/\b((?:bad|poor|eliminate|repair|(?:re)?establish|damag).{0,10} (?:credit|debt)|no credit (?:check|histor|need))/i#,
  q#BANG_GUAR,[l=1]# => q#/\bguaranteed?\!/i#,
  q#BANG_OPRAH,[l=1]# => q#/\boprah!/i#,
  q#BANKING_LAWS,[l=0]# => q#/banking laws/i#,
  q#BILLION_DOLLARS,[l=1]# => q#/[BM]ILLION DOLLAR/#,
  q#BODY_ENHANCEMENT,[l=1]# => q#/\b(?:enlarge|increase|grow|lengthen|larger\b|bigger\b|longer\b|thicker\b|\binches\b).{0,50}\b(?:penis|male organ|pee[ -]?pee|dick|sc?hlong|wh?anger|breast(?!\s+cancer))/i#,
  q#BODY_ENHANCEMENT2,[l=1]# => q#/\b(?:penis|male organ|pee[ -]?pee|dick|sc?hlong|wh?anger|breast(?!\s+cancer)).{0,50}\b(?:enlarge|increase|grow|lengthen|larger\b|bigger\b|longer\b|thicker\b|\binches\b|size)/i#,
  q#CUM_SHOT,[l=1]# => q#/\bcum[ -]?shots?\b/i#,
  q#CURR_PRICE,[l=1]# => q#/\bCurrent Price:/#,
  q#DEAR_BENEFICIARY,[l=1]# => q#/\b(?:De[ae]r\s|At+(?:ention|n):?\s?)(?:\S+\s)?Ben[ei]ficiary\b/i#,
  q#DEAR_SOMETHING,[l=1]# => q#/\bDear (?:IT\W|Internet|candidate|sirs?|madam|investor|travell?er|car shopper|web)\b/i#,
  q#DEAR_WINNER,[l=1]# => q#/\bdear.{1,20}winner/i#,
  q#DIET_1,[l=1]# => q#/\b(?:(?:without|no) (?:exercis(?:e(?! price)|ing)|dieting)|weight.?loss|(?:extra|lose|lost|losing).{0,10}(?:pounds|weight|inches|lbs)|burn.{1,10}fat)\b/i#,
  q#DRUGS_SMEAR1,[l=1]# => q#/(?:Viagra|Valium|Xanax|Soma|Cialis){2}/i#,
  q#DRUG_ED_CAPS,[l=1]# => q#/\b(?:CIALIS|LEVITRA|VIAGRA)/#,
  q#DRUG_ED_GENERIC,[l=1]# => q#/\bGeneric Viagra\b/#,
  q#DRUG_ED_ONLINE,[l=1]# => q#/\bviagra .{0,25}(?:express|online|overnight)/i#,
  q#DRUG_ED_SILD,[l=1]# => q#/\bsildenafil\b/i#,
  q#DX_TEXT_03,[l=1]# => q#/\b[A-Z]{3} Media (?:Group|Relations)\b/#,
  q#EM_ROLEX,[l=1]# => q#/[^\s\w.]rolex/i#,
  q#EXCUSE_24,[l=1]# => q#/you(?:'ve|'re| have| are)? receiv(?:e|ed|ing) this (?:advertisement|offer|special|recurring|paid).{0,16}\b(?:by either|because)/i#,
  q#EXCUSE_4,[l=1]# => q#/To Be Removed,? Please/i#,
  q#EXCUSE_REMOVE,[l=1]# => q#/to be removed from.{0,20}(?:mailings|offers)/i#,
  q#FIN_FREE,[l=1]# => q#/\bfinancial(?:ly)? (?:free|independen)/i#,
  q#FORWARD_LOOKING,[l=1]# => q#/\bcontains forward-looking statements\b/i#,
  q#FREE_PORN,[l=1]# => q#/\bfree (?:porn|xxx|adult)/i#,
  q#FREE_QUOTE_INSTANT,[l=1]# => q#/free.{0,12}(?:(?:instant|express|online|no.?obligation).{0,4})+.{0,32}\bquote/i#,
  q#FSL_THIS_IS_ADV,[l=1]# => q#/This is an advertisement\./#,
  q#GTUBE,[l=1]# => q#/XJS\*C4JDBQADN1\.NSBN3\*2IDNEN\*GTUBE-STANDARD-ANTI-UBE-TEST-EMAIL\*C\.34X/#,
  q#GUARANTEED_100_PERCENT,[l=0]# => q#/100% GUARANTEED/i#,
  q#HK_SCAM_N2,[l=1]# => q#/\bnext of kin\b/i#,
  q#HK_SCAM_N8,[l=1]# => q#/\byour compensation\b/i#,
  q#IMPOTENCE,[l=1]# => q#/\b(?:impotence (?:problem|cure|solution)|Premature Ejaculation|erectile dysfunction)/i#,
  q#INVESTMENT_ADVICE,[l=1]# => q#/\binvestment advice/i#,
  q#JOIN_MILLIONS,[l=1]# => q#/\bjoin (?:millions|thousands)\b/i#,
  q#KAM_ADVERT3,[l=1]# => q#/AllExpiringDomains.com/i#,
  q#KAM_BODY,[l=0]# => q#/{_BODY_HTML}/i#,
  q#KAM_CANSPAM,[l=1]# => q#/(full compliance with the U.S. Federal-?Can-?Spam-Act|provides CAN-SPAM compliant email|consistent with the provisions of the CAN-SPAM Act|compliance with the CanSpam Act)/is#,
  q#KAM_HOLLY,[l=0]# => q#/1 0 2 0 N H o l l y w o o d W a y /i#,
  q#KAM_OVERPAY,[l=1]# => q#/O . V . E . R . P . A . Y/i#,
  q#KAM_PERPARK,[l=0]# => q#/P e r i m e t e r P a r k C e n t e r/i#,
  q#KAM_PUBLIC,[l=1]# => q#/obtained your email address from a publicly available list|find your mail in public forum/is#,
  q#KAM_VIAGRA1,[l=0]# => q#/V I A G R A|C I A L I S|V A L I U M|X A N A X/i#,
  q#KAM_VIAGRA2,[l=0]# => q#/(?:Xan|Som|CIA|VAL|VIA|Pro|Amb|Lev|Mer) (?:Xan|Som|CIA|VAL|VIA|Pro|Amb|Lev|Mer) (?:Xan|Som|CIA|VAL|VIA|Pro|Amb|Lev|Mer)/i#,
  q#KAM_VIAGRA3,[l=1]# => q#/(?:Xan|Som|CIA|VAL|VIA|Pro|Amb|Lev|Mer)( \w )(?:ax|lis|ra|ium)/i#,
  q#KAM_VIAGRA5,[l=1]# => q#/(V [1li|\]] [a&] G R A|VljAG+R+A)/i#,
  q#LIVE_PORN,[l=1]# => q#/\blive .{0,9}(?:fuck(?:ing)?|sex|naked|girls?|virgins?|teens?|porno?)\b/i#,
  q#LOCAL_TEST1,[l=1]# => q#/myspamtest12341234/#,
  q#LONG_TERM_PRICE,[l=1]# => q#/long\W+term\W+(target|projected)(\W+price)?/i#,
  q#LOOPHOLE_1,[l=1]# => q#/loop-?hole in the banking/i#,
  q#LOW_PRICE,[l=1]# => q#/\blow.{0,4} (?-i:P)rice/i#,
  q#MALE_ENHANCE,[l=0]# => q#/male enhancement/i#,
  q#MARKETING_PARTNERS,[l=1]# => q#/\b(?:marketing|network) partner|\bpartner (?:web)?site/i#,
  q#MILLION_USD,[l=1]# => q#/Million\b.{0,40}\b(?:United States? Dollars?|USD)/i#,
  q#MONEY_BACK,[l=0]# => q#/money back guarantee/i#,
  q#MORE_SEX,[l=1]# => q#/increased?.{0,9}(?:sex|stamina)/i#,
  q#NOT_ADVISOR,[l=0]# => q#/not a registered investment advisor/i#,
  q#NO_MEDICAL,[l=1]# => q#/\bno medical exam/i#,
  q#NO_PRESCRIPTION,[l=1]# => q#/N[o0].{1,10}P(?:er|re)scr[i1]pt[i1][o0]n.{1,10}(?:n[e3][e3]d[e3]d|requ[1i]re|n[e3]c[e3]ssary)/i#,
  q#ONE_TIME,[l=1]# => q#/\bone\W+time (?:charge|investment|offer|promotion)/i#,
  q#ONLINE_PHARMACY,[l=1]# => q#/\bonline pharmacy|\b(?:drugs|medications) online/i#,
  q#PREST_NON_ACCREDITED,[l=1]# => q#/prestigi?ous\b.{0,20}\bnon-accredited\b.{0,20}\buniversities/i#,
  q#PRICES_ARE_AFFORDABLE,[l=1]# => q#/\baffordable .{0,10}prices\b/i#,
  q#REFINANCE_NOW,[l=1]# => q#/time to refinance|refinanc\w{1,3}\b.{0,16}\bnow\b/i#,
  q#REFINANCE_YOUR_HOME,[l=1]# => q#/\brefinance your(?: current)? (?:home|house)\b/i#,
  q#REMOVE_BEFORE_LINK,[l=1]# => q#m{(?:no thanks|not interested|unsubscribe here).{0,5}http://}i#,
  q#REPLICA_WATCH,[l=1]# => q#/\breplica.{1,20}rolex/i#,
  q#SHORT_TERM_PRICE,[l=1]# => q#/short\W+term\W+(target|projected)(\W+price)?/i#,
  q#STOCK_ALERT,[l=1]# => q#/\bstock alert/i#,
  q#STRONG_BUY,[l=0]# => q#/strong buy/i#,
  q#TVD_ACT_193,[l=1]# => q#/\bact of (?:193|nineteen thirty)/i#,
  q#TVD_APPROVED,[l=1]# => q#/you.{1,2}re .{0,20}approved/i#,
  q#TVD_INCREASE_SIZE,[l=1]# => q#/\bsize of .{1,20}(?:penis|dick|manhood)/i#,
  q#TVD_LINK_SAVE,[l=1]# => q#/\blink to save\b/i#,
  q#TVD_PH_REC,[l=1]# => q#/\byour .{0,40}account .{0,40}record/i#,
  q#TVD_PH_SEC,[l=1]# => q#/\byour .{0,40}account .{0,40}security/i#,
  q#TVD_QUAL_MEDS,[l=1]# => q#/\bquality med(?:ication)?s\b/i#,
  q#TVD_SECTION,[l=1]# => q#/\bSection (?:27A|21B)/i#,
  q#TVD_VISIT_PHARMA,[l=1]# => q#/Online Ph.rmacy/i#,
  q#T_EMRCP,[l=1]# => q#/\bExcess (?:Maximum )?Return Capital (?:Profits?|Funds?)\b/i#,
  q#UNCLAIMED_MONEY,[l=1]# => q#/\bunclaimed\s(?:assets?|accounts?|mon(?:ey|ies)|balance|funds?|prizes?|rewards?|payments?|deposits?)\b/i#,
  q#URG_BIZ,[l=1]# => q#/urgent.{0,16}(?:assistance|business|buy|confidential|notice|proposal|reply|request|response)/i#,
  q#VIA_GAP_GRA,[l=1]# => q#/\bvia.gra\b/i#,
  q#__ACCESS_RESTORE,[l=1]# => q#/\bto (?:(?:restore|regain) access|(?:remove|uplift) (?:the|this) suspens|continue using your (?:account|online))/i#,
  q#__ACCESS_REVOKE,[l=1]# => q#/(?:temporary|permanent) (?:de-?activation|removal) of your (?:\w{1,30} )?(?:access|account)/i#,
  q#__ACCOUNT_DISRUPT,[l=0]# => q#/ensure (?:that )?your (?:account|access) is not (?:disrupted|suspended|interrupted)/i#,
  q#__ACCOUNT_ERROR,[l=0]# => q#/your account (?:is|appears to be) (?:incorrect|missing|in error|invalid)/i#,
  q#__ACCOUNT_UPGRADE,[l=1]# => q#/(?:upgrade (?:of )your (?:account|access)|your (?:access|account) is[\w\s]{0,40}being upgraded)/i#,
  q#__ACH_CANCELLED_02,[l=1]# => q#/(?:rejected|cancel+ed|declined|your)[-_ ](?:(?-i:ACH)|direct[-_ ]deposit)[-_ ](?:payment|transfer|transaction|declin(?:ed|ing))/i#,
  q#__ACH_CANCELLED_03,[l=1]# => q#/\bwire[-_ ]?(?:payment|transfer|transaction)[-_ ](?:(?:was|is)[-_ ])?(?:rejected|cancel+ed|declined|disabled|not[-_ ]accepted|(?:technical )?error)/i#,
  q#__ACH_CANCELLED_04,[l=1]# => q#/\bregarding[-_ ]your[-_ ]direct[-_ ]deposit[-_ ]via[-_ ](?-i:ACH)/i#,
  q#__ADMAIL,[l=1]# => q#/(?:\b|_)ad-?(?:mail|message)s?(?:\b|_)/i#,
  q#__AFF_LOTTERY,[l=0]# => q#/(?:lottery|winner)/i#,
  q#__AFR_UNION,[l=1]# => q#/\bafrican\sunion\b/i#,
  q#__AGREED_RATIO,[l=1]# => q#/\b(?:agreed|sharing)\s(?:ratios?|percent\w+)\b/i#,
  q#__AM_DYING,[l=1]# => q#/\b(?:am\s(?:\S+\s)?dying|terminally\sill|cancer|en\sphase\sterminale|(?:become|is|devenu|maladie)\sincurable|que\sje\smeurs)\b/i#,
  q#__AUTO_ACCIDENT,[l=0]# => q#/auto(?:mobile)? accident/i#,
  q#__BACK_SCRATCH,[l=1]# => q#/\bmutual+y?\s(?:benefi(?:t|cial)|interest)\b/i#,
  q#__BANK_DRAFT,[l=1]# => q#/\bbank\sdraft/i#,
  q#__BARRISTER,[l=1]# => q#/\b(?:barrister|solicitor at law|barr\.)/i#,
  q#__BENIN,[l=1]# => q#/\bb(?:e|=E9|[\xe9]|[\xc3][\xa9])nin\b/i#,
  q#__BIGNUM_EMAILS,[l=1]# => q#/\b(?:thousand|million|\d[,\d]{4,})\s(?:(?!and|or|your|place|baby)\w+\s)?(?:e-?mail\saddresses|leads|names)\b/i#,
  q#__BODY_XHTML,[l=0]# => q#/<x-html>/i#,
  q#__BOUNCE_NEVER_SEE,[l=1]# => q#/\bThis is an autoresponder. I'll never see your message\b/i#,
  q#__BOUNCE_NONWORKING,[l=1]# => q#/\bYou have reached a non.?working address.  Please check\b/i#,
  q#__BOUNCE_NO_RESEND,[l=1]# => q#/\bPlease do not resend your original message\./#,
  q#__BOUNCE_OOO_2,[l=1]# => q#/\bI ?.m away until .{10,20} and am unable to read your message\b/#,
  q#__BOUNCE_OOO_3,[l=1]# => q#/\bI am currently out of the office\b/#,
  q#__BURKINA_FASO,[l=1]# => q#/\bburkina\s?faso\b/i#,
  q#__CAN_HELP,[l=1]# => q#/\bcan help\b/i#,
  q#__CASHPRZ,[l=1]# => q#/cash prize of/#,
  q#__CHARITY,[l=1]# => q#/\b(?:charit(?:y|[ai]ble)|orphans?|homeless|orphelins|sans\sabri)\b/i#,
  q#__CLEAN_MAILBOX,[l=1]# => q#/\b(?:(?:e-?mail|mail\s?box|violation:|(?-i:CLICK)) (?:quota size|clean(?:-?up))|clean ?up click ?here)\b/i#,
  q#__CLICK_HERE,[l=1]# => q#/\bclick\shere\b/i#,
  q#__COMPENSATION,[l=1]# => q#/\b(?:compensat(?:e|ion)|recompensed?|ausgleich)\b/i#,
  q#__CONTACT_ATTY,[l=1]# => q#/\bcontact(?:er)?\s(?:my|(?:de\s)?mon)\s(?:barrister|attou?rney|lawyer|avocat|gestionnaire)\b/i#,
  q#__CONTACT_YOU,[l=1]# => q#/\b(?:contact(?:ing)\syou|vous\scontacter?)\b/i#,
  q#__COURIER,[l=1]# => q#/\bcourier\s(?:company|service)\b/i#,
  q#__DBLCLAIM,[l=1]# => q#/avoid double claiming/#,
  q#__DEAL,[l=1]# => q#/\b(?:(?:business|financial|this|the|mutual|die(?:se)?r?|cette|profitable)\s(?:deal|transa[ck]tion|proposal|off[er]{2}|venture|suggestion|partnership)|your\spartnership)/i#,
  q#__DECEASED,[l=1]# => q#/\b(?:the|my|your|der|du|le|meu?)\s(?:deceased|late|verstorbenen|d(?:i|e|=E9|[\xe9]|[\xc3][\xa9])funto?|d(?:e|=E9|[\xe9]|[\xc3][\xa9])nt|falecido)\b/i#,
  q#__DESTROY_ME,[l=1]# => q#/\b(?:destroy|hunt|quemar)\sm[eyi]\b/i#,
  q#__DESTROY_YOU,[l=1]# => q#/\bdestroy\syou/i#,
  q#__DIED_IN,[l=1]# => q#/\bdied\sin\b/i#,
  q#__DIPLOMATIC,[l=1]# => q#/\bdiplomatic\b/i#,
  q#__DLND_ATTACH,[l=1]# => q#/\bdownload\sthe\sattach(?:ed|ment)\b/i#,
  q#__DORMANT_ACCT,[l=1]# => q#/\b(?:(?:dormant|abandoned|left\s?over)\s(?:account|fund|transaction|sum|deposit)|fonds\sdorment)/i#,
  q#__DOS_BODY_FRI,[l=1]# => q#/\bfri(?:day)?\b/i#,
  q#__DOS_BODY_MON,[l=1]# => q#/\bmon(?:day)?\b/i#,
  q#__DOS_BODY_SAT,[l=1]# => q#/\bsat(?:day)?\b/i#,
  q#__DOS_BODY_STOCK,[l=1]# => q#/\bstock\b/i#,
  q#__DOS_BODY_SUN,[l=1]# => q#/\bsun(?:day)?\b/i#,
  q#__DOS_BODY_THU,[l=1]# => q#/\bthu(?:r(?:s(?:day)?)?)?\b/i#,
  q#__DOS_BODY_TICKER,[l=1]# => q#/\b[A-Z]{4}\.(?:OB|PK)\b/#,
  q#__DOS_BODY_TUE,[l=1]# => q#/\btue(?:s(?:day)?)?\b/i#,
  q#__DOS_BODY_WED,[l=1]# => q#/\bwed(?:nesday)?\b/i#,
  q#__DOS_CORRESPOND_EMAIL,[l=1]# => q#/correspond with me using my email/#,
  q#__DOS_DROP_ME_A_LINE,[l=1]# => q#/Drop me a line at/#,
  q#__DOS_EMAIL_DIRECTLY,[l=1]# => q#/(?:Email m[a-z]?e|address) direc(?:tl|lt)y at/#,
  q#__DOS_FIN_ADVANTAGE,[l=1]# => q#/\bfinancial advantage/i#,
  q#__DOS_I_AM_25,[l=1]# => q#/I a.?m 25/#,
  q#__DOS_I_DRIVE_A,[l=1]# => q#/I drive a/#,
  q#__DOS_LET_GO_JOB,[l=1]# => q#/I was (?:let go|fired|layed off|dismissed) from a job I h(?:el|a)d for (?:2\d years|\d{3} months)/#,
  q#__DOS_LINK,[l=1]# => q#/\blink\b/#,
  q#__DOS_MEET_EACH_OTHER,[l=1]# => q#/(?:meet each other|[Mm]ay ?be we can meet)/#,
  q#__DOS_MY_OLD_JOB,[l=1]# => q#/my old job/#,
  q#__DOS_PERSONAL_EMAIL,[l=1]# => q#/personal email at/#,
  q#__DOS_STEADY_COURSE,[l=1]# => q#/\bsteady (?:and increasing )?course\b/i#,
  q#__DOS_STRONG_CF,[l=1]# => q#/\bstrong cash flow/i#,
  q#__DOS_TAKING_HOME,[l=1]# => q#/Taking home \d (?:digit level|figures) in \d{1,2} months/#,
  q#__DOS_WRITE_ME_AT,[l=1]# => q#/[Ww].?r.?i.?t.?e me at/#,
  q#__DRUGS_ANXIETY2,[l=1]# => q#/\bAlprazolam\b/i#,
  q#__DRUGS_ANXIETY8,[l=1]# => q#/\bklonopin\b/i#,
  q#__DRUGS_ANXIETY9,[l=1]# => q#/\brivotril\b/i#,
  q#__DRUGS_ANXIETY_VAL,[l=0]# => q#/valium/i#,
  q#__DRUGS_ANXIETY_XAN,[l=1]# => q#/xan[ae]x/i#,
  q#__DRUGS_DIET3,[l=1]# => q#/\bbontril\b/i#,
  q#__DRUGS_DIET4,[l=1]# => q#/\bphendimetrazine\b/i#,
  q#__DRUGS_DIET5,[l=1]# => q#/\bdiethylpropion\b/i#,
  q#__DRUGS_DIET_PHEN,[l=1]# => q#/\bphentermine\b/i#,
  q#__DRUGS_ERECTILE2,[l=1]# => q#/\bV(?:agira|igara|iaggra|iaegra)\b/i#,
  q#__DRUGS_ERECTILE4,[l=1]# => q#/\bC(?:alis|ilias|ilais)\b/i#,
  q#__DRUGS_ERECTILE5,[l=1]# => q#/\b_{0,3}s[_\W]?[i1!|l\xEC-\xEF][_\W]?l[_\W]?d[_\W]?[e3\xE8-\xEB][_\W]?n[_\W]?[a4\xE0-\xE6@][_\W]?f[_\W]?[i1!|l\xEC-\xEF][_\W]?l c[_\W]?[i1!|l\xEC-\xEF][_\W]?t[_\W]?r[_\W]?[a4\xE0-\xE6@][_\W]?t[_\W]?[e3\xE8-\xEB]_{0,3}(?:\b|\s)/i#,
  q#__DRUGS_ERECTILE_C,[l=1]# => q#/\bCialis\b/i#,
  q#__DRUGS_ERECTILE_L,[l=1]# => q#/\bLevitra\b/i#,
  q#__DRUGS_ERECTILE_V,[l=1]# => q#/\bViagra\b/i#,
  q#__DRUGS_MUSCLE2,[l=1]# => q#/\b_{0,3}cycl[o0\xF2-\xF6]b[e3\xE8-\xEB]nz[a4\xE0-\xE6@]pr[i1!|l\xEC-\xEF]n[e3\xE8-\xEB]_{0,3}(?:\b|\s)/i#,
  q#__DRUGS_MUSCLE5,[l=1]# => q#/\bskelaxin\b/i#,
  q#__DRUGS_PAIN11,[l=1]# => q#/\bzebutal\b/i#,
  q#__DRUGS_PAIN12,[l=1]# => q#/\besgic plus\b/i#,
  q#__DRUGS_PAIN2,[l=1]# => q#/\b_{0,3}c[o0\xF2-\xF6]deine_{0,3}\b/i#,
  q#__DRUGS_PAIN_FIO,[l=0]# => q#/fioricet/i#,
  q#__DRUGS_PAIN_VICO,[l=0]# => q#/vicodin/i#,
  q#__DRUGS_PAIN_VIOXX,[l=0]# => q#/vioxx/i#,
  q#__EARLY_DEMISE,[l=1]# => q#/\buntimely\sdeath\b/i#,
  q#__FAILED_LOGINS,[l=1]# => q#/unsuc+es+ful log-?[io]n at+empts/i#,
  q#__FB_COST,[l=1]# => q#/\bcost\b/i#,
  q#__FB_S_STOCK,[l=1]# => q#/\bstock/i#,
  q#__FB_TOUR,[l=1]# => q#/\btour/i#,
  q#__FEES,[l=1]# => q#/\b(?:security|safe\w*|courier|registration|pay|paid|up-?front|processing|delivery|transfer|keeping)[\s\w]{0,15}\s(?:fee|charge)s?\b/i#,
  q#__FOR_SALE_LTP,[l=1]# => q#/00\.? (?:less 10%|LTP)/i#,
  q#__FOR_SALE_NET,[l=1]# => q#/00\.? NET/i#,
  q#__FOR_SALE_OBO,[l=1]# => q#/\bor best offer\b/i#,
  q#__FOR_SALE_PRC_100K,[l=1]# => q#/\bprice:? \$\d\d\d,\d\d\d/i#,
  q#__FOR_SALE_PRC_10K,[l=1]# => q#/\bprice:? \$\d\d,\d\d\d/i#,
  q#__FOR_SALE_PRC_1K,[l=1]# => q#/\bprice:? \$\d,?\d\d\d[.\s]/i#,
  q#__FOUND_YOU,[l=1]# => q#/\b(?:I|we)\sfound\syour?\b/i#,
  q#__FRAUD,[l=1]# => q#/\b(?:de)?fraud/i#,
  q#__FRAUD_AON,[l=1]# => q#/\b(?:confidential|private|alternate|alternative) (?:(?:e-? *)?mail)\b/i#,
  q#__FRAUD_AUM,[l=1]# => q#/\bthe desk of\b/i#,
  q#__FRAUD_AXF,[l=0]# => q#/magnanimity/i#,
  q#__FRAUD_BEP,[l=1]# => q#/\b(?:bank of nigeria|central bank of|trust bank|apex bank|amalgamated bank)\b/i#,
  q#__FRAUD_BGP,[l=1]# => q#/\battached to ticket number\b/i#,
  q#__FRAUD_CKF,[l=0]# => q#/computer ballot system/i#,
  q#__FRAUD_DPR,[l=1]# => q#/\b(?:(?:respond|reply) (?:urgently|immediately)|(?:urgent|immediate|earliest) (?:reply|response))\b/i#,
  q#__FRAUD_ETX,[l=1]# => q#/\byour\b[^.]{0,99}\b(?:contact (?:details|information)|private (?:e?[- ]?mail|telephone|tel|phone|fax))\b/i#,
  q#__FRAUD_EZY,[l=1]# => q#/\b(?:of|the) late president\b/i#,
  q#__FRAUD_FBI,[l=1]# => q#/\bdisburs/i#,
  q#__FRAUD_FCW,[l=0]# => q#/fiduciary agent/i#,
  q#__FRAUD_FVU,[l=0]# => q#/award notification/i#,
  q#__FRAUD_GBW,[l=1]# => q#/god gives .{1,10}second chance/i#,
  q#__FRAUD_IOU,[l=1]# => q#/\b(?:no risks?|risk-? *free|free of risks?|100% safe)\b/i#,
  q#__FRAUD_IOV,[l=1]# => q#/\b(?:no risks?|risky?[- ]{0,3}free|free of risks?|100% safe|v\S{1,3}llig Risikofrei ist)\b/i#,
  q#__FRAUD_IPK,[l=1]# => q#/\b(?:in|to|visit) your country\b/i#,
  q#__FRAUD_IRJ,[l=0]# => q#/(?:finance|holding|securit(?:ies|y)) (?:company|firm|storage house)/i#,
  q#__FRAUD_IRT,[l=1]# => q#/\b(?:compliments? of the|dear friend|dear sir|yours faithfully|season'?s greetings)\b/i#,
  q#__FRAUD_JBU,[l=1]# => q#/\bforeign account\b/i#,
  q#__FRAUD_JNB,[l=1]# => q#/\boperat(?:e|ing)\b[^.]{0,99}\b(?:for(?:ei|ie)gn|off-? ?shore|over-? ?seas?) (?:bank )?accounts?\b/i#,
  q#__FRAUD_JYG,[l=1]# => q#/\bgive\s+you .{0,15}(?:fund|money|total|sum|contact|percent)\b/i#,
  q#__FRAUD_KJV,[l=0]# => q#/(?:claim|concerning) (?:the|this) money/i#,
  q#__FRAUD_LTX,[l=1]# => q#/\bmilli?on (?:.{1,25} thousand\s*)?(?:(?:united states|u\.?s\.?) dollars|(?i:U\.?S\.?D?))\b/i#,
  q#__FRAUD_MCQ,[l=1]# => q#/\btransaction\b.{1,30}\b(?:magnitude|diplomatic|strict|absolute|secret|confiden(?:tial|ce)|guarantee)/i#,
  q#__FRAUD_MLY,[l=1]# => q#/\b(?:reply|respond)\b[^.]{0,50}\b(?:to|through)\b[^.]{0,50}\@\b/i#,
  q#__FRAUD_MQO,[l=0]# => q#/foreign (?:business partner|customer)/i#,
  q#__FRAUD_NEB,[l=0]# => q#/(?:government|bank) of nigeria/i#,
  q#__FRAUD_NRG,[l=0]# => q#/i am contacting you/i#,
  q#__FRAUD_PTS,[l=1]# => q#/\b(?:ass?ass?inat(?:ed|ion)|murder(?:e?d)?|kill(?:ed|ing)\b[^.]{0,99}\b(?:war veterans|rebels?))\b/i#,
  q#__FRAUD_PTX,[l=1]# => q#/\b(?:ass?ass?inat(?:ed|ion)|murder(?:e?d)?|poison(?:e?d)?|kill(?:ed|ing|ers)\b[^.]{0,99}\b(?:war veterans|rebels?)|les tueurs)\b/i#,
  q#__FRAUD_PVN,[l=0]# => q#/as the beneficiary/i#,
  q#__FRAUD_QFY,[l=1]# => q#/\bover-? *(?:invoiced?|cost(?:s|ing)?)\b/i#,
  q#__FRAUD_QXX,[l=1]# => q#/\b(?:my name is|i am) (?:mrs?|engr|barrister|dr|prince(?:ss)?)[. ]/i#,
  q#__FRAUD_RLX,[l=1]# => q#/lott(?:o|ery) (?:co,?ordinator|international)/i#,
  q#__FRAUD_SNT,[l=1]# => q#/\blocate(?: .{1,20})? extended relative/i#,
  q#__FRAUD_TCC,[l=0]# => q#/foreign (?:offshore )?(?:bank|account)/i#,
  q#__FRAUD_TDP,[l=1]# => q#/\b(?:business partner(?:s|ship)?|silent partner(?:s|ship)?)\b/i#,
  q#__FRAUD_THJ,[l=0]# => q#/modalit(?:y|ies)/i#,
  q#__FRAUD_ULK,[l=1]# => q#/\baffidavits?\b/i#,
  q#__FRAUD_UOQ,[l=0]# => q#/vital documents/i#,
  q#__FRAUD_UUY,[l=1]# => q#/\blegitimate business(?:es)?\b/i#,
  q#__FRAUD_WDR,[l=1]# => q#/\bprivate lawyer\b/i#,
  q#__FRAUD_WFC,[l=1]# => q#/\bsecur(?:e|ing) (?:the )?(?:funds?|monies)\b/i#,
  q#__FRAUD_WNY,[l=1]# => q#/\b(?:disburse?(?:ment)?|incurr?(?:ed)?|remunerr?at(?:ed?|ion)|remm?itt?(?:ed|ance|ing)?)\b/i#,
  q#__FRAUD_XJR,[l=0]# => q#/(?:who was a|as a|an? honest|you being a|to any) foreigner/i#,
  q#__FRAUD_XVW,[l=1]# => q#/\bhonest cooperation\b/i#,
  q#__FRAUD_XWW,[l=1]# => q#/\b(?:honest(?:ly)?\sco(?:-?operat(?:e|ion)|llaborat(?:e|ion))|ehrliche\szusammenarbeit|sichere [kc]o+p[eo]ration|col+aboration\swith\sme)\b/i#,
  q#__FRAUD_YJA,[l=0]# => q#/over-invoice/i#,
  q#__FRAUD_YPO,[l=0]# => q#/the total sum/i#,
  q#__FRAUD_YQV,[l=0]# => q#/nigerian? (?:national|government)/i#,
  q#__FRAUD_YWW,[l=1]# => q#/\bfurnish you with\b/i#,
  q#__FRAUD_ZFJ,[l=1]# => q#/\b(?:wife|son|brother|daughter) of the late\b/i#,
  q#__GAPPY_SALES_LEADS,[l=1]# => q#/\b(?:business|e?-?mail|your|marketing|advertising)\s(?!sales|leads|campaign)(?:s\s?a\s?l\s?e\s?s|l\s?e\s?a\s?d\s?s|c\s?a\s?m\s?p\s?a\s?i\s?g\s?n)\b/i#,
  q#__GHANA,[l=1]# => q#/\bghana\b/i#,
  q#__HAS_WON_01,[l=1]# => q#/\bque ha ganado\b/i#,
  q#__HK_LOTTO_1,[l=1]# => q#/\b(?:(?:inter)?national|foundation|mercato|univers|euro ?million|e-?mail|euro-pw|bill ?gates|swiss|prestige|cristal|am.ricaine|coca.?cola|fiduciary|department) ?lot(?:eri[ej]|t(?:ery|o))/i#,
  q#__HK_LOTTO_2,[l=1]# => q#/\blot(?:eri[ej]|t(?:ery|o)) ?(?:(?:inter)?national|foundation|mercato|univers|euro ?million|e-?mail|euro-pw|bill ?gates|swiss|prestige|cristal|am.ricaine|coca.?cola|fiduciary|department)/i#,
  q#__HK_LOTTO_BALLOT,[l=1]# => q#/\b(?:promotional|on.?line|computer|internet|e-?mail|fran.aise) (?:ballot|draw|sweepstake)/i#,
  q#__HK_LOTTO_JACKPOT,[l=1]# => q#/\bmega jackpot\b/i#,
  q#__HK_LOTTO_STAATS,[l=1]# => q#/\bstaatsloteri/i#,
  q#__HUSH_HUSH,[l=1]# => q#/\b(?:confiden[tc]i[ae]l(?:\b|ity\b|it(?:=E9|[\xe9]|[\xc3][\xa9]))|private\b|secr[e\xe8](?:te?|cy)\b|sensitive\b|concealed\b|obscured?\b|discre(?:et|tion)\b|very\sdiscrete|top\ssecret|vertraulich(?:en)?\b|geheim\b|priv(?:e|=E9|[\xe9]|[\xc3][\xa9]))/i#,
  q#__INHERIT_PMT,[l=1]# => q#/\binheritance\spayment\s/i#,
  q#__INTL_BANK,[l=1]# => q#/\b(?:international\s(?:\w+\s)?bank|banque\sinternationale)\b/i#,
  q#__INVEST_COUNTRY,[l=1]# => q#/\binvest\sin\syour?\scountry\b/i#,
  q#__INVEST_MONEY,[l=1]# => q#/\binvest(?:ir)?\s(?:this|ces|d[ae]s|sur ce|de ces)\s(?:money|f[ou]nds?)\b/i#,
  q#__ISO_2022_JP_DELIM,[l=1]# => q#/\e\$B/#,
  q#__IVORY_COAST,[l=1]# => q#/\b(?:Cote\s?D.Ivoire|Ivory\s?Coast|Costa\sde\sMarfil)\b/i#,
  q#__I_INHERIT,[l=1]# => q#/\b(?:I|eu)\s[a-z\s]{0,30}(?:inherited|herdei)\b/i#,
  q#__I_WILL_YOU,[l=1]# => q#/\bwill(?:ed)?\s(?:[a-z\s]{0,20}(?:fortune|money|\$[\d,]+[a-z]{0,9})\s)?to\syou\b/i#,
  q#__JAPANESE_UCE_BODY,[l=1]# => q#/(?:L\$>5Bz|EE;R%a!<%k)(?:8x|9-)9p/#,
  q#__KAM_1LINE1,[l=1]# => q#/(free score and report|Did you overpay\?)/is#,
  q#__KAM_ABOUT2,[l=0]# => q#/Spyware/i#,
  q#__KAM_ACNE3,[l=0]# => q#/proactiv/i#,
  q#__KAM_ACNE4,[l=0]# => q#/Online Gift Rewards/i#,
  q#__KAM_ADDRESS1,[l=1]# => q#/204 N. El Camino Real|CocoMedia|17 Patchogue Road|1128-274 Royal Palm Beach|(848|500) N. Rainbow Dr. Ste [hash]?(2511|300)|CMI Free Stuff|Vista Del Mar Productions|by SuperClub|Buil tech Services|eMarketing Alliance|aSHARPi Media|Plaza Neptuno|Satell Center for Executive Education|Pacific Shores Investments|rx ?unit|Cascio Interstate Music|R. Allen Media|The Only Virginia Team|Ban Amnesty Now|Intrust Domains|8001 Irvine Center Dr|American Arbitration Association, 1633 Broadway|\+962 79 668 2974|7025 County Rd. 46A|1001 E.Hillsdale Blvd|New Heights Development and Research|Red Base Interactive|RateMarketplace|WORLD COMPANY REGISTER|WhatsApp Inc|Streetdirectory Pte Ltd|4399 Church Street, Brooklyn|Mobie Concepts, Inc.|Clickingz IT Research Lab|Leadz[,\.].?Co|DLF Cyber City Gurgaon India|4447 N Central Expressway, Office [hash]110|Two Allen Center|5401 Hangar Court|Pimsleur Approach|1600 JFK Boulevard, 3rd|Business Who's Who|Who's Who Among Executives|Buena Vista Catalogue|10620 Southern Highlands|Ashray Medical Center|Bethany Christian Services|Ashland.Avenue.{0,4}95761|Preston Energy/i#,
  q#__KAM_ADVANCE2,[l=0]# => q#/Advance Details/i#,
  q#__KAM_ADVANCE3,[l=0]# => q#/Pre-Approved/i#,
  q#__KAM_ADVERT1,[l=1]# => q#/email advertising/is#,
  q#__KAM_ADVERT2,[l=1]# => q#/instant traffic (to your website|and sales)/is#,
  q#__KAM_ADVERT3,[l=1]# => q#/Email Ad Broadcast|Double OPT IN list/is#,
  q#__KAM_ALARM2,[l=1]# => q#/free Quotes|burglaries|wireless.security.camera|Guard Your Family|ADT is Number One/i#,
  q#__KAM_ALT1,[l=1]# => q#/reply to my alternative E-?mail/is#,
  q#__KAM_ANA1,[l=1]# => q#/(anatrim|Green ?Tea|cortitherm|PHENTERTHIN|Phentremine|Acai Ultra|Civ-xR|WuYi Tea|Wu-?Yi Source|FRS Healthy Energy|Acai Berry|Chinese secret|Ephedra|Cholestapro|ColonMedic|Pure Cleanse|AcaiBurn|Acai Elite|Garcinia|Chlorogenic Acid|green coffee)/i#,
  q#__KAM_AP3,[l=0]# => q#/American Grants and Loans Catalog/i#,
  q#__KAM_AQUA1,[l=1]# => q#/Aqua Globe/is#,
  q#__KAM_AQUA2,[l=1]# => q#/watering your plants/is#,
  q#__KAM_AQUA3,[l=1]# => q#/while on vacation/is#,
  q#__KAM_ARREST2,[l=0]# => q#/Instant Checkmate|dirty Truth/i#,
  q#__KAM_ASIAN2,[l=0]# => q#/Adoring Asian/i#,
  q#__KAM_AUGER2,[l=0]# => q#/Awesome Auger/i#,
  q#__KAM_BACK1,[l=1]# => q#/NATIONAL|backgrounds in seconds|Instant Checkmate/#,
  q#__KAM_BACK2,[l=1]# => q#/(Property & Personal history|Asset & Background) (Investigation|Search)|check anyone/is#,
  q#__KAM_BACK3,[l=1]# => q#/(background check|detective|investigator|investigate backgrounds|arrest.record)/is#,
  q#__KAM_BARK1,[l=1]# => q#/Bark.Off|petzoom sonic|comfy control harness/i#,
  q#__KAM_BBB2,[l=1]# => q#/consumer's *(?:worry|uneasiness|anxiety|disturbance|concern|trouble)/i#,
  q#__KAM_BBB3,[l=0]# => q#/has been registered the above|(?:visiting|review at) a link below|above-referenced complaint/i#,
  q#__KAM_BBB4,[l=1]# => q#/about your *(?:glance|belief|judgment)/i#,
  q#__KAM_BIZ1,[l=1]# => q#/You always need new cards|free full color business cards|get 250 more ?- ?free|business card offer|500 business cards/is#,
  q#__KAM_BLOOD3,[l=0]# => q#/Secret Big Pharma|conspiracy/i#,
  q#__KAM_BLOOD4,[l=0]# => q#/Marine Essentials|this mineral/i#,
  q#__KAM_BLOOD5,[l=0]# => q#/Anti-Aging Expert/i#,
  q#__KAM_BLOOD6,[l=0]# => q#/Blood pressure/i#,
  q#__KAM_BUS1,[l=0]# => q#/business proposal/i#,
  q#__KAM_BUS2,[l=0]# => q#/sensitive by nature/i#,
  q#__KAM_BUS3,[l=0]# => q#/have not met/i#,
  q#__KAM_BUS4,[l=0]# => q#/view my attach/i#,
  q#__KAM_CAR2,[l=0]# => q#/buying a new car|dream car|new car you want|free auto insurance(?:-| )quote|save money on your auto|roadside assistance|extended warranty/i#,
  q#__KAM_CAR3,[l=1]# => q#/unbelievable payment terms|no commitment|free price quote|get competitive quotes|offering better rates|no obligation quote|Pay Later|No risk|save up to \d+%/i#,
  q#__KAM_CARD2,[l=1]# => q#/(laughing kitty|crazy cat) card|enjoy your awesome card|Click on your .{0,15}card('s)? (link|direct www address) below|To see your custom .{0,15}card, simply click on the (link below|following)|(as you can see on the ecard)|^your .{1,15}card link:$|I bet your wife won\'?t do this for you|Your temporary Login Info|temp\.? password id|pics I took of my Ex-Wife|card will be aviailable/i#,
  q#__KAM_CARD3,[l=1]# => q#/I['`]m in hurry, but i still love you...|has (issued you a greeting|made you an Ecard)|^(Follow this link:|click (here to enter our secure server:))?\s*?http:\/\/\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}|eCard, open attached/i#,
  q#__KAM_CARDEAL3,[l=1]# => q#/201\d Closeout pricing|New Vehicles near you/i#,
  q#__KAM_CAREER1,[l=1]# => q#/Hospitals need you|Medical Billing and Coding/is#,
  q#__KAM_CAREER2,[l=1]# => q#/Get your Healthcare Degree|Billing and Coding degree/is#,
  q#__KAM_CASINO1,[l=0]# => q#/Elite World Casino/i#,
  q#__KAM_CASINO2,[l=0]# => q#/Online Casino/i#,
  q#__KAM_CEP1,[l=0]# => q#/Job Prospect Newsletter/i#,
  q#__KAM_CEP2,[l=0]# => q#/legitimate verifiable degree/i#,
  q#__KAM_CEP3,[l=0]# => q#/Career Education program/i#,
  q#__KAM_CEP4,[l=1]# => q#/(MBA|CEP)/#,
  q#__KAM_CEP5,[l=0]# => q#/degree\/certificates/i#,
  q#__KAM_CEP6,[l=1]# => q#/\d (week|month)/i#,
  q#__KAM_CHANGELOG2,[l=0]# => q#/as promised chnglog update/i#,
  q#__KAM_CHECK1,[l=0]# => q#/delivery fee for your che(que|ck) draft/i#,
  q#__KAM_CHECK2,[l=0]# => q#/let me know when you recieve your money/i#,
  q#__KAM_CHOSEN3,[l=0]# => q#/You (were|have been) (recently )?chosen/i#,
  q#__KAM_CIGAR3,[l=0]# => q#/Thompson Cigar|Premium Cigar/i#,
  q#__KAM_CLICK,[l=0]# => q#/Please click on the link below|Copy and paste this link into your internet browser/i#,
  q#__KAM_COBRA3,[l=0]# => q#/find cobra health/i#,
  q#__KAM_COLLECT2,[l=0]# => q#/No Fee/i#,
  q#__KAM_COLLECT3,[l=0]# => q#/collection professionals/i#,
  q#__KAM_COLLECT4,[l=0]# => q#/recovery rate/i#,
  q#__KAM_COMPANY2_1,[l=1]# => q#/Member Services MGM, LLC/is#,
  q#__KAM_COMPROMISED3,[l=1]# => q#/\d{1,2}[\\\/]\d{1,2}[\\\/]\d{2,4} \d{1,2}\:\d{1,2}\:\d{1,2} (AM|PM)/#,
  q#__KAM_COMPROMISED4,[l=1]# => q#/How are you\? Look at this.{0,70}Do you know about this site|look at this site right now|I found (an amazing|great) site|hey\. please have a look|have a look right now/i#,
  q#__KAM_CREDIT2,[l=1]# => q#/View (all 3 reports|your credit score|your up.to.the.minute credit)|(EXPERIAN|Transunion|Equifax) report|check my credit score|3.free credit scores|credit restoration|changes in your.score|get your \d+ score online|3 major sources|all three bureau|all 3 credit score/i#,
  q#__KAM_CREDIT3,[l=1]# => q#/NO COST|it's on us|3 companies for free|freescore360|Scoresense|score.report(?:ing)?.team|stand in the rating scales|view your higher credit/i#,
  q#__KAM_CREDIT4,[l=1]# => q#/CHANGES TO YOUR CREDIT[- ]SCORE|credit score has changed|Triple Bureau Credit Alerts|score\s+may\s+have\s+(been)?\s*changed|ThinkCredit/i#,
  q#__KAM_DEBT1,[l=1]# => q#/(debts disappear|reduce your payments|piling bills|creditors|late bills|vanish some of your bills|reduce your payments|looming bills|all that debt|outstanding debt|debt.{0,7}accumulated|all my debt|penalties,? and fees are gone|banking laws|select legal|change your life|get out of .?d.?e.?b.?t|Free[- ]Credit Report|debt relief options|are you in debt|pay off all your debt|get better rates|credit card debt)/is#,
  q#__KAM_DIET2_3,[l=0]# => q#/secret to being skinny|doctors? are raving/i#,
  q#__KAM_DIRECT3,[l=0]# => q#/(Complimentary|Visitor|attend our open house|30-day member|VIP Pass|Wholesale Direct Pricing|guest pass and catalog)/i#,
  q#__KAM_DIRECT4,[l=1]# => q#/Direct ?Buy/i#,
  q#__KAM_DISCAIR3,[l=0]# => q#/Fly Cheap in Business Class/i#,
  q#__KAM_DISCLAIMER1,[l=0]# => q#/receives compensation/i#,
  q#__KAM_DOMAIN1,[l=0]# => q#/Domain (opportunity|notification|release|Availability|club)|Notification for Domain/i#,
  q#__KAM_DOMAIN2,[l=0]# => q#/(?:available|listed) (?:by|for|at|in) auction|confirm interest in (this domain|owning)|capturing this domain/i#,
  q#__KAM_DOMAIN3,[l=1]# => q#/(?:have|own) a domain (that is )?.{0,5}similar|(have|own) a similar domain|offer on the Domain|similar to your (current )?domain|Domain Division/i#,
  q#__KAM_DON3,[l=1]# => q#/donnob\.(?:biz|net)|emarketnow.com|watersolutiontoday.com/i#,
  q#__KAM_DON4,[l=0]# => q#/\$1,000 A Day ATM|J\.O\.B\./i#,
  q#__KAM_DRILL1,[l=0]# => q#/drilling/i#,
  q#__KAM_DRILL2,[l=0]# => q#/oil (company|partnership|and gas rights)/i#,
  q#__KAM_DRILL3,[l=1]# => q#/(exceed(ed)? .{0,10}expectations|see your brokers website)/i#,
  q#__KAM_DRILL4,[l=0]# => q#/(buy today|Check this deal out)/i#,
  q#__KAM_DRUG1,[l=1]# => q#/Quality and cheap|premier quality|supor-collosal mixture|Discount-?Pharmacy/is#,
  q#__KAM_DRUG2,[l=1]# => q#/cheaper|redeem in bulk and save|bigger quantities and Save|drugstore accredi[dt]ations|economical (?:value|amount)/is#,
  q#__KAM_DRUG2_3,[l=1]# => q#/Medi?cati[o0]ns|desired meds|favou?red (rx)?med|buy remedies|drug store|medicants|medicaments|sexual stim|sex stim|pain killer|(purchase|loved|preferred|favou?rite) (?:rx.?)?(deal|med)[sz]|rx.?Meds?.?deal|buy your meds|choice of meds|Rx.?(deal|Med|Sale)|v[i1]agra|medz.special|loved meds|(rx|medication) ?discount/i#,
  q#__KAM_DRUG2_4,[l=1]# => q#/Purchase|grab hold|click here|at[_ ~]your[_ ~]finger[_ ~]?tip|placing your order|questions about drugs|prescription is not|don't care about prescription|without a doctor|no need for a doctor|affor[df]able.prices|best daily rx|Fav.Prescript|unmatched.prices|rx.med/i#,
  q#__KAM_DRUG2_5,[l=1]# => q#/0nline|hassle[~-]free|favored rx|branded solutions|branded remedies|v[1i]cod[!i]n|Penhtremine|prxpills|ultimaterxhere|insanerx|speedymed4u|mightymeds1|coolestrxhere|hotrxmedspot|topshoprx|mightyrxhere|qualityrxmedz|legitrxlife|dealsformeds|simplyrxdeals|bestrxlight|ezprescriptz|reliablerxsource1|freetrusted-rx|hotmedsourcehere|CabinetOfMeds|mytrusted-rx|RxwarehouseHere|WarehouseofRxMeds|GreatrxMedsRus|rxmedsrus|(come by|Come to|Check Out) our web site|browse [0o]ur (website|selection)|Visit_0ur Web|Order_Now|available_this week|(buy|order) (n[0o]w|today|right.now|instantly|at [0o]nce|immediately)|check it out today|ord3r|0rder|0rd3r|browseour|rx ?unit/i#,
  q#__KAM_DRUG2_6,[l=1]# => q#/(Express|Prompt|Day|Trusty|Trustworthy|Reliable|fast|true|discreet|confidential|rapid)[_ ~\.]?Shippin|anonymous packing|shipped.right.away/i#,
  q#__KAM_DRUG4,[l=1]# => q#/click to buy|no previous doctors direction|No prescript[oi]{2}n needed|no script necessary|medicine assistance supplier|mail[- ]?order medicine/is#,
  q#__KAM_DUCHESS3,[l=1]# => q#/Mr. Media Group|BLM Marketing Services|4801 l[yi]nton b/i#,
  q#__KAM_DUCHESS6,[l=0]# => q#/For account number:/i#,
  q#__KAM_EBAY1,[l=0]# => q#/Succeed on ebay|thousands with ebay|ebay success|money-making secret/i#,
  q#__KAM_EBAY2,[l=0]# => q#/Auction success kit|Great Money Maker|documented program|Chuck Mullaney|more bills than money/i#,
  q#__KAM_EGG1,[l=1]# => q#/Egg Genie/is#,
  q#__KAM_EMAILPHISH1,[l=0]# => q#/Please login to complete update process/i#,
  q#__KAM_FAKEDELIVER1,[l=1]# => q#/courier couldn.?t make the delivery|Courier was unable to deliver|courier company was not able to deliver/i#,
  q#__KAM_FAKEDELIVER3,[l=1]# => q#/DHL/#,
  q#__KAM_FAKEDELIVER5,[l=1]# => q#/Fed ?ex/i#,
  q#__KAM_FAKEDELIVER7,[l=0]# => q#/USPS/i#,
  q#__KAM_FAKEDELIVER9,[l=1]# => q#/CARGO/#,
  q#__KAM_FAKEPDF1,[l=1]# => q#/Download PDF Reader.Writer/is#,
  q#__KAM_FAKEPDF2,[l=1]# => q#/Reader 2010/is#,
  q#__KAM_FARM3,[l=0]# => q#/(blueberry|Tomatoe?) giant/i#,
  q#__KAM_FDA1,[l=1]# => q#/statements.{1,10}not.{1,10}evaluated.{1,10}(FDA|Food ?(and|&) ?Drug Administration)/i#,
  q#__KAM_FDA2,[l=1]# => q#/not intended to diagnose,? treat,? cure,? or prevent/i#,
  q#__KAM_FDA3,[l=0]# => q#/FDA Recall/i#,
  q#__KAM_FLASH1,[l=1]# => q#/Flash Player Code: \d\d/i#,
  q#__KAM_FLASH2,[l=0]# => q#/Flash Player Update/i#,
  q#__KAM_FLEXHOSE3,[l=1]# => q#/stretch but not kink|flex.?hose/i#,
  q#__KAM_FOOTBALL3,[l=0]# => q#/Mercato/i#,
  q#__KAM_FOOTBALL4,[l=0]# => q#/Football/i#,
  q#__KAM_GALLERY2,[l=1]# => q#/(Infinite|Multi|Elite|Extreme|Complete|Instant|Ultimate|Multi|approved|Free|HD|Guaranteed|Unreal) Access|(Ultimate|Babes|Elite|Extreme|P.?o.?r.?n) Collection|(Girls|Adu.?lt|Babes|Celeb.?rities) Passwords|(Ultimate|p.?o.?r.?n|extreme|elite|Girls) gallery|HD Video|Access Now/i#,
  q#__KAM_GALLERY4,[l=1]# => q#/(Fantastic|Insane|Mega|Extreme|Extreme|New|Many|Fresh|Your|Check) P.?o.?r.?n|cele.?brities elite|(Insane|P.?o.?r.?n|More|Awesome|All|Mega) Model|(Your|Mega|Asian|Bad|Cool|Fresh|Real|Awesome|More) Girl|(Sweet|Incredible|Insane|The|Grand) chick|(Many|New|Infinite|Cool|All) Cele.?b|The N.?u.?des|(Infinite|Awesome|Many|Sweet|Bad|Get|Fresh|Hot|More|Black) Babe|Amat.?e.?urs|(All|Fresh|Fantastic|The|Mega) Adu.?lt|(Extraordinary) Chicks/i#,
  q#__KAM_GAS1,[l=1]# => q#/Gas prices are at an? all time high|\$\d per gallon/i#,
  q#__KAM_GAS2,[l=1]# => q#/We have a solution|save \d+ cents per gallon/i#,
  q#__KAM_GERMAN_BUSINESS_CONTACTS3,[l=0]# => q#/German business phone numbers/i#,
  q#__KAM_GERMAN_BUSINESS_CONTACTS4,[l=0]# => q#/Unlimited exportation capabilities/i#,
  q#__KAM_GEVALIA1,[l=1]# => q#/Gevalia Kaffe|premium coffee delivered/is#,
  q#__KAM_GEVALIA2,[l=1]# => q#/(Gevalia coffee lover's|I love coffee) kit/is#,
  q#__KAM_GEVALIA3,[l=1]# => q#/No Further Obligation/is#,
  q#__KAM_GIFT1,[l=1]# => q#/(Claim your free \$500 Target Gift Card|complimentary gift-?card|received a Victoria's Secret Giftcard|\$500 airline gift card|\$1000 gift card for you to shop|\$\d+ gift card|Secret gift card)/is#,
  q#__KAM_GIFT2,[l=1]# => q#/(unsubscribe from this advertiseme(tn|nt)|exit future communications|to unsubscribe from this|to stop any offers from us)/is#,
  q#__KAM_GIFT3,[l=0]# => q#/every girl loves to buy|do you need a new|offer pass you by/i#,
  q#__KAM_GIFT4,[l=0]# => q#/card will be yours free|card on us|buy you the dyson animal/i#,
  q#__KAM_GIFT5,[l=0]# => q#/member incentive program/i#,
  q#__KAM_GIFTCERT1,[l=0]# => q#/Our gift to you/i#,
  q#__KAM_GIFTCERT2,[l=1]# => q#/\$\d+ gift certificate/i#,
  q#__KAM_GINA3,[l=0]# => q#/Genetic Information Nondiscrimination Act/i#,
  q#__KAM_GINA4,[l=0]# => q#/mandatory poster|remain in compliance|GINA regulations/i#,
  q#__KAM_GIVE1,[l=0]# => q#/receive your gift/i#,
  q#__KAM_GIVE2,[l=1]# => q#/laptop giveaway|deliver your dell.? laptop/i#,
  q#__KAM_GIVE3,[l=0]# => q#/answering a short survey/i#,
  q#__KAM_GIVE4,[l=0]# => q#/verify your shipping address/i#,
  q#__KAM_GOOGLE2,[l=0]# => q#/learn how to earn|automated income kit|online from home|as much money as you wish|be the boss/i#,
  q#__KAM_GOOGLE3,[l=1]# => q#/tons of money|making \$[\d,]*s with Google|extra cash|making serious money/i#,
  q#__KAM_GOOGLE4,[l=0]# => q#/with Google|Google Pie|Google Cash/i#,
  q#__KAM_GOOGLEPHISH1,[l=0]# => q#/copy of the signed agreement/i#,
  q#__KAM_GOVT2,[l=0]# => q#/government funding/i#,
  q#__KAM_GOVT3,[l=0]# => q#/complimentary information kit/i#,
  q#__KAM_GOVT4,[l=1]# => q#/No.Money?.{0,4}No.Problem/i#,
  q#__KAM_GRANT1,[l=0]# => q#/government grant/i#,
  q#__KAM_GRANT2,[l=0]# => q#/find out if you qualify/i#,
  q#__KAM_GRANT3,[l=0]# => q#/discontinue from this promotion/i#,
  q#__KAM_GRASS3,[l=0]# => q#/Grass Seed On Steroids|rich beautiful lawn|Patch Perfect Seeds|Grow Grass (anywhere|in the shade)/i#,
  q#__KAM_GUN1,[l=0]# => q#/Keep and Bear Arms/i#,
  q#__KAM_HAIRTRANS3,[l=1]# => q#/hair restoration|man look as young|losing your hair|hair ?loss/i#,
  q#__KAM_HANGOVER3,[l=0]# => q#/hangover patch/i#,
  q#__KAM_HEALTH1,[l=1]# => q#/as low as \$\d+\s*(per|\/)\s*month|at \$\d+ including dental/i#,
  q#__KAM_HEALTH2,[l=1]# => q#/save up to \d+% on health insurance|affordable health coverage|quality term life insurance|nationalhealthxchange.com/i#,
  q#__KAM_HEALTH2_1,[l=0]# => q#/affordable health coverage/i#,
  q#__KAM_HEART3,[l=1]# => q#/Knowing this could very well save your life|\d+ second trick|[hash]1 Trick|Prevent(ing)? A Heart Attack/i#,
  q#__KAM_HIDDEN_URI1,[l=1]# => q#/\[DOT\]com/is#,
  q#__KAM_HIDDEN_URI2,[l=1]# => q#/replace "?\[DOT\]/is#,
  q#__KAM_HIP1,[l=0]# => q#/hip replacement|medical alert/i#,
  q#__KAM_HIP2,[l=0]# => q#/implant recall|recall list/i#,
  q#__KAM_HOME1,[l=0]# => q#/YOUR HOME|Federal Housing Assistance Program/i#,
  q#__KAM_HOME2,[l=0]# => q#/Build your equity faster|refund is not reversible/i#,
  q#__KAM_HOME3,[l=1]# => q#/tax saving plans|\d+K Mortgage Credit/i#,
  q#__KAM_HOMESALE3,[l=0]# => q#/Cash Offer for Your Home/i#,
  q#__KAM_HONEY1,[l=1]# => q#/Intacct Corporation|Miles Technologies|EcoPhones|businessbrief\.com|pbpinfo\.com|pbp-executivereports\.net|b21pubs\.com|sonar6\.com|cheetahsend\.com|voip-news|microcappress.com|myrtlebeachnow|sosonlinebackup.com|Landslide Technologies|The Performance Institute|ASMI Corporate|Kaseya|Cascio|CarProperty|HSRUpdates.com/i#,
  q#__KAM_HOODIA3,[l=1]# => q#/(?:fat loss product|sur?p?press appetite|Reduce Your Appetite)/is#,
  q#__KAM_HOSE3,[l=0]# => q#/pocket hose/i#,
  q#__KAM_HSR1,[l=1]# => q#/hsrupdates.com|progressiverailroading.com/i#,
  q#__KAM_IDENTNET2,[l=0]# => q#/ADVERTISE WITH IDENTITY NETWORK/i#,
  q#__KAM_INK1,[l=1]# => q#/Ink (and|&|n) Toner|SimplyInk|101 inks|1ink|printer ink sale/is#,
  q#__KAM_INSTOCK,[l=0]# => q#/in stock/i#,
  q#__KAM_INSURE2,[l=1]# => q#/find better Health Insurance Rates Today|get information about health coverage|protect your family|overpay for auto insurance|been recently,? lowered|gas prices are going up|Auto Insurnace go with it|no examination|get (?:a )?free quote|have been.{0,2}reduced|AutoWarranty|plans as low as|plans starting at|complete your health profile|Secure \d+k coverage|why pay more for.{0,30}coverage|save up to \d+%|accuquote|Life Insurance Coverage|protect.your.family.{1,20}insurance|Protect home and belonging|Affordable Care Act/i#,
  q#__KAM_JOB1,[l=1]# => q#/let go from (a job|my employment) I held for.{1,19} (month|year|forever|life)/is#,
  q#__KAM_JOB2,[l=1]# => q#/twice as much/is#,
  q#__KAM_JOINT3,[l=1]# => q#/TFX.?(?:health|flex)|tflex/i#,
  q#__KAM_JOINT4,[l=0]# => q#/Joint Relief|effective as glucosamine/i#,
  q#__KAM_JOINT5,[l=0]# => q#/free bottle/i#,
  q#__KAM_JUDGE1,[l=1]# => q#/(unpaid court|(un-?collected|unsatisfied) judgments)/is#,
  q#__KAM_JUDGE2,[l=1]# => q#/(funds|receive what) you are (due|owed)/is#,
  q#__KAM_JUDGE3,[l=1]# => q#/collect your money/is#,
  q#__KAM_JUDGE4,[l=0]# => q#/judgment/i#,
  q#__KAM_LANG3,[l=1]# => q#/pimsleur|Language in just \d+ Day/i#,
  q#__KAM_LASIK3,[l=1]# => q#/free (?:Lasik )?eval|\d+ per eye/i#,
  q#__KAM_LIKE1,[l=1]# => q#/been working (extremely|very) hard on my friend's website/is#,
  q#__KAM_LIKE2,[l=1]# => q#/a link from .{1,54} would be greatly appreciated/is#,
  q#__KAM_LIKE3,[l=1]# => q#/(link exchange|in return to me linking back)/is#,
  q#__KAM_LIKE4,[l=1]# => q#/HTML code for the link/is#,
  q#__KAM_LIKE5,[l=1]# => q#/I apologize if this message was sent, in error/is#,
  q#__KAM_LINGERIE4,[l=0]# => q#/Exotic modelling videos/i#,
  q#__KAM_LIST3,[l=1]# => q#/price\:|prices for our director/is#,
  q#__KAM_LIST4,[l=1]# => q#/(?:database|list|[\d,]+ (total records|e-?mails))/is#,
  q#__KAM_LIST5,[l=1]# => q#/(reply with "stop" as a subject|Send an email with "rem" in the subject to discontinue|put "cease" in the subject of an email|for termination of this e?mail|reply with .{1,8} in the subject)|you will have your email taken off|for the datacard/is#,
  q#__KAM_LOTTO2,[l=1]# => q#/((ticket|serial|lucky) number|secret pin ?code|pin number|batch number|reference number|promotion date|lottery|sweepstake|\d+ lucky recipients|for claim and inquiring)/is#,
  q#__KAM_LOTTO3,[l=1]# => q#/(won|claim|cash prize|pounds? sterling|over \$500|award sum of US\$|NOTIFICATION FOR CASH AID)/is#,
  q#__KAM_LOTTO4,[l=1]# => q#/(claims (office|agent|manager)|lottery coordinator|(certificate|fiduciary) (officer|agent)|fiduaciary claims|accredited agent|payment agency board|promotion manager|promotions? department|Name of +Agent:|executive secretary|claims & Management|lottery approved courier)/is#,
  q#__KAM_LOTTO5,[l=1]# => q#/(POWERBALL LOTTO|freelotto group|Royal Heritage Lottery|(British|UK) National( Online)? Lottery|U\.?K\.? Grand Promotions|Lottery Department UK|Euromillion Loteria|Luckyday International Lottery|International Lottery|Euro - Afro Asian Sweepstake|urawinner|Free Lotto Sweepstakes|PROMOTION DEPARTMENT|PROMOTION\/PRIZE AWARD|Nederlandse Internationale Loterij|EURO MILLIONS|APPLE LOTTERY ONLINE|MSW MEGA JACKPOT|MICROSOFT EMAIL PROMO|MSNlottery|ECOWAS|Nigeria|National Lottery)/is#,
  q#__KAM_LOTTO6,[l=1]# => q#/(Dear (Award|Consultation Prize|Lucky) Winner|Winning Notification|Attention:Winner|Dear:? Winner|Amount won:|Sincere Congratulations|Lucky Numbers:|you are a winner|prize attached|prize notification|claims requirement|winning number|winning sum|payout of|qualification number)/is#,
  q#__KAM_MAID3,[l=0]# => q#/Pre-Screened Housekeepers/i#,
  q#__KAM_MAILBOX1,[l=0]# => q#/mailbox has exceeded the storage limit/i#,
  q#__KAM_MAILBOX2,[l=0]# => q#/re-validate your mailbox/i#,
  q#__KAM_MAILER1,[l=0]# => q#/{!firstname_fix}/i#,
  q#__KAM_MASCARA3,[l=0]# => q#/smartlash/i#,
  q#__KAM_MED1,[l=1]# => q#/e.?c.?o.?n.?o.?m.?i.?z.?e.{1,10}med/i#,
  q#__KAM_MEDICAL1,[l=0]# => q#/million who suffer from|suffered from organ failure/i#,
  q#__KAM_MEDICAL2,[l=0]# => q#/Safe - Natural - Effective/i#,
  q#__KAM_MEDTOUR1,[l=1]# => q#/medical.tourism/i#,
  q#__KAM_MEDTOUR2,[l=0]# => q#/lowest cost in India/i#,
  q#__KAM_MEMBER3,[l=1]# => q#/date|dating|eharmony|Find.Your.Perfect.Match/i#,
  q#__KAM_MOVIE2,[l=0]# => q#/Movie Extra/i#,
  q#__KAM_NEWS2,[l=0]# => q#/(?:Hello|hey|hi)!/i#,
  q#__KAM_NEW_CREDITCARD3,[l=0]# => q#/Select your new card|Increase Your Spending|Higher Limit/i#,
  q#__KAM_NIGERIAN1,[l=1]# => q#/(?:payment officer|personal treasurer|experienced marketers|Chairman of the Finance Committee|contact my secretary|field of Financial Services|Head of Human Resources|Public Relation Officer|field of Business Services|payment agent|representing partner|vacancy in my company|representative\/book ?keeper|executor|search and selection of both experienced|retired chief economist|foreign partner|diplomatic courier|senior auditor|online book-?keeper)/is#,
  q#__KAM_NIGERIAN2,[l=1]# => q#/(?:looking for dynamic representative|seek your partnership|new online business model|seek to transfer this money|completely legal activity|never ask you to pay or invest|in search of trustworthy representatives|establishing a new liaison network|rec[ei]{2}ving payment on our behalf|assist me in transferring those funds|make money at home|requiring rep to work on a part time|part time job\/full time|organization for the good work of the lord|job search directory|investor willing to invest in lebanon|invest in Real Estate|Your kind assistance|next of kin)/is#,
  q#__KAM_NIGERIAN2_2,[l=0]# => q#/barrister|director of central bank|bank director/i#,
  q#__KAM_NIGERIAN2_3,[l=0]# => q#/high court|central bank|payment center/i#,
  q#__KAM_NIGERIAN2_4,[l=1]# => q#/e-?mail id is found among those that have been scammed|paid the fee for your cheque draft|contact the bank director/i#,
  q#__KAM_NIGERIAN2_5,[l=0]# => q#/fund code|cheque|bank draft/i#,
  q#__KAM_NIGERIAN2_6,[l=0]# => q#/full contact information requested|need your contacts informations|your bank account information/i#,
  q#__KAM_NIGERIAN2_7,[l=0]# => q#/bank/i#,
  q#__KAM_NIGERIAN2_8,[l=0]# => q#/courier|diplomat agent|direct wire transfer/i#,
  q#__KAM_NIGERIAN2_9,[l=0]# => q#/scam|don't let them know that it is money|bank transfer charges/i#,
  q#__KAM_NIGERIAN3,[l=1]# => q#/(?:\d{1,2}\% (?:commission on each transaction|of the total will be set|will be mapped out|is made available to you|of the total sum for your partner|of the money for your effort|for\s+sales)|pay for performance|floating deficit|for your compensation|financial independence|their financial dreams|work from home part\s*-?\s*time|employing your services|get extra income|deduct your weekly salary \d\d%|transfer of the funds|make successful career at us|you will get \d{1,2}% on each|funds can be directed to your account as a grant|reasonable parentage|dormant domiciliary account|share would be \d+\%|pay you \d+%)/is#,
  q#__KAM_NIGERIAN4,[l=1]# => q#/(?:American oil merchant|independent contractor|removallink|claim the funds|international corporation|bank draft|becoming our contract staff|contractual employment|customers\s*in Europe,\s*America|new partner from UK|great investment site|money orders|cashiers check|access to the funds|piloting the business|moving the funds|next of kin)/is#,
  q#__KAM_NIGERIAN5,[l=0]# => q#/Western Union Money Transfer|Money Gram|form of Money Orders|to apply for this job, please send the following|process our payments|not traceable|risk free transation|transfer to a designated bank account|inheritance return/i#,
  q#__KAM_NOTIFY2,[l=1]# => q#/[2-9] friend request( |\b)|sell your personal|mandatory validation|verify your Account|unread messages/i#,
  q#__KAM_NURSE3,[l=1]# => q#/nurses (?:are NOW in high.?demand|are needed)|nursing Degree/i#,
  q#__KAM_OBFURL1,[l=1]# => q#/A\s+D\s+I\s+L\s+I\s+Z\+E\s+R\s+.\s+C\s+O\s+M/i#,
  q#__KAM_OPRAH1,[l=0]# => q#/airfare/i#,
  q#__KAM_OPRAH2,[l=0]# => q#/hotel/i#,
  q#__KAM_OPRAH3,[l=0]# => q#/oprah/i#,
  q#__KAM_OZ3,[l=1]# => q#/burn off your (?:body.?)?fat|(?:burn away|burn|melt) your fat|fox news video|melt the extra pounds|lost \d+ lbs/i#,
  q#__KAM_PAYDAY3,[l=0]# => q#/Financial Relief|need to borrow/i#,
  q#__KAM_PEEL1,[l=1]# => q#/Titan Peeler/is#,
  q#__KAM_PEST3,[l=0]# => q#/revolutionary pes?t control system/i#,
  q#__KAM_PET3,[l=0]# => q#/pet health insurance/i#,
  q#__KAM_PHISH2_2,[l=1]# => q#/Virginia Credit Union|Lloyds|HSBC/is#,
  q#__KAM_PHISH2_4,[l=1]# => q#/unauthori[sz]ed use/i#,
  q#__KAM_PHISH2_5,[l=0]# => q#/account suspension|temporary locked/i#,
  q#__KAM_PHISH2_6,[l=0]# => q#/confirm your online banking details/i#,
  q#__KAM_PHISH2_7,[l=0]# => q#/extra security check/i#,
  q#__KAM_PHISH3_2,[l=1]# => q#/accessed by someone else./#,
  q#__KAM_PIC1,[l=1]# => q#/(tired|bored) (this )?(today|tonight|evening|morning|afternoon)|saw your email address|online right now|can name me|found you on this site|I am alone|my next boyfriend|blonde with blue|like the girls/is#,
  q#__KAM_PIC2,[l=1]# => q#/(nice girl|2\d years old|25 y.o. girl|pretty russian|I russian girl|age is 25|long legs, cute|see my pictures|I'm 19|searching for a bad girl|meet with such attractive)/is#,
  q#__KAM_PIC3,[l=1]# => q#/like to chat|feelings can be true|like to have friendship|friendly guy|gave me your photos|waiting on you|found your pictures|send me a note|more information about you/is#,
  q#__KAM_PIC4,[l=1]# => q#/(like to share some of my pics|some (?:great )?pictures of me|sending some of my pictures|To see my pic|hope you like my pic|will reply with my pics|show you some pic|chat with me and see|that's my photo)|will send you my pictures|view my profile|describe yourself|chat with me|bad girl|view your snapshot|want to watch video/is#,
  q#__KAM_PIC5,[l=0]# => q#/picture|photo|my pics/i#,
  q#__KAM_PILLS2,[l=0]# => q#/be (thrifty|smart|clever), buy your (pills|drugs|medications)/i#,
  q#__KAM_POLITICS2,[l=1]# => q#/Minuteman Civil Defense Corps|National Campaign Fund|Right vs Left|Restore America PAC|penntransportation.com|getliberty.org|Americans for Limited Government/i#,
  q#__KAM_POLY2,[l=0]# => q#/The End of Barack Obama/i#,
  q#__KAM_POWER1,[l=0]# => q#/hoveround/i#,
  q#__KAM_PRIV1,[l=0]# => q#/private message|horny|sweet ass/i#,
  q#__KAM_PRIV2,[l=0]# => q#/(personal|private) video/i#,
  q#__KAM_PRIV3,[l=0]# => q#/the attache?ment|attached file/i#,
  q#__KAM_PRODUCT2,[l=0]# => q#/phones for discerning individuals/i#,
  q#__KAM_PROPHET3,[l=0]# => q#/Dear Christian Friend/i#,
  q#__KAM_PROPHET4,[l=0]# => q#/Christian Media Ministry/i#,
  q#__KAM_PROPHET5,[l=0]# => q#/prophecy article/i#,
  q#__KAM_QTJARS3,[l=1]# => q#/qtjars/#,
  q#__KAM_QTJARS4,[l=1]# => q#/private message/#,
  q#__KAM_QUOTA1,[l=0]# => q#/Mailbox Quota Has Exceeded|exceeded its storage limit/i#,
  q#__KAM_QUOTA2,[l=0]# => q#/Limited Access|termination of your email/i#,
  q#__KAM_REAL1,[l=1]# => q#/(^|\b)RE market/is#,
  q#__KAM_REAL2,[l=0]# => q#/(crashing|declining)/i#,
  q#__KAM_REAL2_1,[l=0]# => q#/(?:Property available|on the water|costa rica)/i#,
  q#__KAM_REAL2_2,[l=0]# => q#/(?:pre-development prices|finish building|torn down to build|exclusive place)/i#,
  q#__KAM_REAL2_3,[l=1]# => q#/(?:unbelievable deals|buyer with CA[s\$]h|pennies.on.the.dollar)/i#,
  q#__KAM_REAL2_4,[l=0]# => q#/(?:home sites|raw land|vacation home)/i#,
  q#__KAM_REAL2_5,[l=0]# => q#/(?:developers|estates|buyer flying in|retirement plans)/i#,
  q#__KAM_REAL3,[l=1]# => q#/(vacation|second) (home|place)/is#,
  q#__KAM_REFI2,[l=1]# => q#/(Free Evaluation (?:online|on your (?:current )?home loan)|No hidden costs|no strings attached|good credit or not|personalized consultation|in need of loan|consolidation loan|loan processing|apply by sending|loan of any amount|clean up any inacccuracies|lock in saving|save on monthly mortgage|absolutely no cost|underwater)|Reverse.?Mortgage/is#,
  q#__KAM_REFI3,[l=1]# => q#/(restructure (?:proposal|program|opportunity|your loan)|switch from an adjustable rate to a fixed|new lending program|(low|reasonable) interest (loan|rate)|lowest monthly payment|\d% interest|unsecured personal|better credit terms|lower your mortgage|low-interest refinance|see your credit score|credit score.{1,15}updated|refi with HARP)/is#,
  q#__KAM_REFI5,[l=1]# => q#/([\d,]{5,6}|\d{2}\s*%) savings|principal \d+% less/is#,
  q#__KAM_REFI6,[l=1]# => q#/((?:reduce your monthly payment|save you) (between )?\d{2}\s*%|save yourself hundreds of dollars|great rate available|completely unsecured|instantly connect with\s+lenders|get you back on the right financial|get report today|protect against identity|know your credit score|crazy payments)/is#,
  q#__KAM_REFI7,[l=1]# => q#/(?:loan product|equity cash|monthly house payment|mortgage|no up front fees|seasoned equity|pay off high rate cards|ARM Program|credit is less than perfect|credit (score )?will not disqualify|plastic money|charge card balances|we offer out loans|floating loan scheme|unsecured guaranteed|President.?s new program|Home Affordable Refinance Program)/is#,
  q#__KAM_REHAB3,[l=0]# => q#/(?:drug|alcohol) (recovery|rehab|dependenc|addict|treatment)|help for alcoholism|life from alcohol|end your drinking|think about rehab/i#,
  q#__KAM_REP1,[l=1]# => q#/Replace \[?[-!~\.]\]? with \./is#,
  q#__KAM_REP2,[l=1]# => q#/www\s+[-!~\.]/i#,
  q#__KAM_REP2_1,[l=1]# => q#/(Just|Please|all you need to do is to) (copy|type):? (www\s)?.{0,10}[\[\(]([-!~\.]|dot)[\]\)]/is#,
  q#__KAM_REP2_2,[l=0]# => q#/in your (IE|internet|explorer|browser)/i#,
  q#__KAM_REP3_1,[l=1]# => q#/\*omit empty spaces/is#,
  q#__KAM_REP3_2,[l=1]# => q#/.\s+(COM|org|net|info)$/i#,
  q#__KAM_RICH1,[l=1]# => q#/financial.success story/i#,
  q#__KAM_RICH2,[l=1]# => q#/see me on the channel \d news/i#,
  q#__KAM_RICH3,[l=0]# => q#/talking about my blog/i#,
  q#__KAM_RICH4,[l=1]# => q#/bec.me financially independent/i#,
  q#__KAM_RXPLAN3,[l=0]# => q#/gap coverage/i#,
  q#__KAM_SANTA2,[l=0]# => q#/Santa Letter|Letter from Santa|sent by Santa/i#,
  q#__KAM_SANTA3,[l=1]# => q#/the .?perfect.? gift|personalized letter/i#,
  q#__KAM_SCOOTER3,[l=0]# => q#/the scooter store/i#,
  q#__KAM_SEARCH2,[l=0]# => q#/search engine/i#,
  q#__KAM_SEARCH3,[l=0]# => q#/(first on|all of) the major search|not ranked number one|Website promotion/i#,
  q#__KAM_SEARCH4,[l=0]# => q#/guaranteed type of exposure|free website search engine optimi|increase your revenue|improve your website traffice|website rank higher/i#,
  q#__KAM_SELL2,[l=0]# => q#/Easy Money/i#,
  q#__KAM_SELL3,[l=0]# => q#/Selling Credit Cards/i#,
  q#__KAM_SELLPHONE1,[l=0]# => q#/Turn iphones into cash/i#,
  q#__KAM_SELLPHONE2,[l=0]# => q#/used or broken|pre-paid envelope/i#,
  q#__KAM_SEO2,[l=0]# => q#/(?:top|first page) (?:in|of) (?:Google|MSN|Yahoo|Bing)|rank number one|top page rank|guarantee you 1st/i#,
  q#__KAM_SEO3,[l=1]# => q#/never find your web site|major search engines|link.building|WEBSITE AUDIT REPORT/i#,
  q#__KAM_SEO4,[l=1]# => q#/No upfront fees|SEO Specialists|online marketing services|S.?E.?O.? Company in INDIA/i#,
  q#__KAM_SEO5,[l=0]# => q#/more traffic guaranteed|results in thirty day|top 5 organic|high revenue/i#,
  q#__KAM_SEO6,[l=1]# => q#/will not get your website banned|Google.?s SEO policies|six month ongoing campaign/i#,
  q#__KAM_SETTING2,[l=0]# => q#/security upgrade|Maintenance Process on our email system /i#,
  q#__KAM_SETTING3,[l=1]# => q#/settings?.zip/i#,
  q#__KAM_SEX04_1,[l=1]# => q#/(curative|medicinal|salutary|wholesome|beneficial|satisfaction) effect|(first-rated|splendid) drugs|(yellow|blue|famos) (tablet|pill)|good medical supplies|(commendable|valuable) medicines|canadian pharmacy/is#,
  q#__KAM_SEX04_2,[l=1]# => q#/fun in bed|(bed|night) adventures|aid your bed|(lift|heave|ascent|hoist|raise|boost|aid) your (belove|love|darling|sex|sweet)|sexuality with assistance|ascent your sweet|bed experience|love sexuality/is#,
  q#__KAM_SEX04_4,[l=1]# => q#/longer your tool|sexual experience|empower your (belove|sex)|sweet sex|(not bad|great|nice|special|awesome|free) bonus|sex all night|lovers package/is#,
  q#__KAM_SEX05_2,[l=0]# => q#/buy rubber friends|big bait in your pants|she sees your size|women will be funk|biggest tool|immense monster|women will be daydreaming|have so much meat|prolonging your size|last a lot longer/i#,
  q#__KAM_SEX06_1,[l=0]# => q#/more fire and passion/i#,
  q#__KAM_SEX1,[l=1]# => q#/(?:double[ -]?headed|pornstar|huge weenie|male power|\d\dper\. of men|male enhancement product|enlarge patch|boost up your virility|clinically tested|improve manhood|Bigger Pen..is|Big Penis|incredible gains to your manhood|muscular manhood|nights unsatisfied|climaxes|sensual enhancer|love instrument|bigger member|excitement with girls|fucker|animal sex)/i#,
  q#__KAM_SEX2,[l=1]# => q#/(?:(\b|^)cunt(\b|$)|busty|interracial|hardcore|peni(s|le) enlarge|generic quality|enlarge your manhood|stone-hard manhood|XXL Dick|intense pleasure|spend a night with you|efficient medicine|turn on your wife|with your boner|dick dangl)/i#,
  q#__KAM_SEX4,[l=0]# => q#/(?:bring your girlfriend back|satisfied with their size|penis so huge and heavy|more semen|volume of your loads|wondercum|ejaculate|bargain offers on medic|improve xxx|improve your lovemaking|youngest teen|teen pics|monster in his pants|female orgasms|extreme penetration)/i#,
  q#__KAM_SEX_EXPLICIT4,[l=1]# => q#/fucked hardcore|dildoes her tight ass|kinky watersports|schoolgirls? slut|teens? porn|first anal(\b|$)|pussy lips|kinky lesbian|sucks? cock|rub puss|spreads? cunt|fetish babe|kinky pee|muffdived \& fuck|deepthroat on knees/i#,
  q#__KAM_SHAM3,[l=0]# => q#/ShamWow/i#,
  q#__KAM_SHAM4,[l=0]# => q#/20(X| times) its weight/i#,
  q#__KAM_SHARP1,[l=0]# => q#/sharp for life/i#,
  q#__KAM_SHARP2,[l=0]# => q#/yoshiblade/i#,
  q#__KAM_SHARP3,[l=0]# => q#/zirconium oxide/i#,
  q#__KAM_SHARP4,[l=0]# => q#/ceramic knife/i#,
  q#__KAM_SHOP1,[l=1]# => q#/chosen to participate as a Mystery Shopper/is#,
  q#__KAM_SHOP2,[l=1]# => q#/Do you like to shop/is#,
  q#__KAM_SHOP3,[l=1]# => q#/make money while you shop/is#,
  q#__KAM_SILD2,[l=1]# => q#/(XtraSize+|Sildenafil Citrate)/i#,
  q#__KAM_SKIN3,[l=1]# => q#/Ped ?Egg|Belisi|Botox|Gabamed|Sera Concepts|Purelift|nuforia|natural collagen|complimentary trials|nugenics|marine essentials|Nufori?a/i#,
  q#__KAM_SKIN4,[l=1]# => q#/feet feel smooth and healthy|calluses and dead skin|silky smooth skin|tighter skin|\d years younger|anti[- ]aging|look younger|free trial|lose 25 years|angered plastic surge|quick and easy trick|anti-?aging|blood pressure low/i#,
  q#__KAM_SKYPE4,[l=1]# => q#/Promo Code: \d/i#,
  q#__KAM_SLICEOMATIC3,[l=0]# => q#/Slice-o-matic/i#,
  q#__KAM_SMOKE1,[l=1]# => q#/smoke anywhere|electronic cig|smoking alternative|prado|e.?-?cigs/i#,
  q#__KAM_SMOKE4,[l=1]# => q#/No carbon monoxide|Smokeless Direct|No Tobacco|no tar|no cancer|quit smoking|electronic cig|e-?cig/i#,
  q#__KAM_SNORE3,[l=0]# => q#/stop snoring|zquiet|Jaw Supporter/i#,
  q#__KAM_SOCKET3,[l=0]# => q#/side socket/i#,
  q#__KAM_SOFTWARE3,[l=0]# => q#/Fix file errors/i#,
  q#__KAM_SOFTWARE4,[l=0]# => q#/download for no cost|FREE Software|Free Analysis|Free Report/i#,
  q#__KAM_SOLAR3,[l=0]# => q#/power bill in half|go solar|approved for solar|solar system saves|reduce your electric/i#,
  q#__KAM_SPAM2,[l=1]# => q#/www.redshop-biz.com/i#,
  q#__KAM_SPAMKING1,[l=1]# => q#/This advertisement is presented by/is#,
  q#__KAM_SPAMKING2,[l=1]# => q#/If you have any questions or concerns regarding this communication, please send correspondence/is#,
  q#__KAM_SPAMKING3,[l=1]# => q#/To .{0,30}(?:unsubscribe|stop|remove) .{0,35}(?:email|messages) from third party advertisers/is#,
  q#__KAM_SPAMKING4,[l=1]# => q#/notify .{0,30} that you no longer wish to receive (?:promotional )?messages/is#,
  q#__KAM_SPAMKING5,[l=1]# => q#/This (communication|message) was delivered to you by/is#,
  q#__KAM_SPAMKING6,[l=1]# => q#/(?:please send|Forward postal) correspondence to/is#,
  q#__KAM_STAR1,[l=0]# => q#/REMOVE ("\*"|space) (in the above|to make the) link/i#,
  q#__KAM_STOCK2_1,[l=0]# => q#/(good trader|trading experience|bad trading day|hard trading day|FREE Stock Market Outlook|Market Watch)/i#,
  q#__KAM_STOCK2_2,[l=0]# => q#/(easy cash|losses and victories|backstage trading|market facts|succeed in trading|destined to skyrocket)/i#,
  q#__KAM_STOCK2_3,[l=0]# => q#/stock/i#,
  q#__KAM_STOCK2_4,[l=0]# => q#/trader/i#,
  q#__KAM_STOCK3,[l=1]# => q#/([sS].?ymbol|Sym|SYM|SYMB|Symb|SYMBOL|SYmN|SYMN|Symn|Ticker|TICKER|Lookup|PINKSHEETS)\s*[-_:]\s*[A-Z0-9][-\._ ]?[A-Z0-9][-\._ ]?[A-Z0-9][-\._ ]?[A-Z0-9]/#,
  q#__KAM_STOCKBULL,[l=1]# => q#/bull (run|market)/is#,
  q#__KAM_STOCKJUMP,[l=1]# => q#/(up|jumps) \d\d(\.\d)?\%/i#,
  q#__KAM_STOCKOTC,[l=1]# => q#/(OTC|OTC ?BB|OTC Pink Sheets|NASDAQ|StockWatch):/is#,
  q#__KAM_STOCKSCTR,[l=1]# => q#/(energy sector|mineral rights|mineral wealth|natural resources|gold deposits)/is#,
  q#__KAM_STOCKSHR,[l=1]# => q#/\b(Shares|Investments|invest|Stock|acquisitions?|broker|joint[ -]?venture|underperforming|(uncap|ventilated|public(ity)?) on friday|dividend opportunities|set your buy|financial safe haven|before the bell)\b/i#,
  q#__KAM_STOCKTIP1,[l=1]# => q#/(?:Reynaldo's Mexican Food|RYNL)/is#,
  q#__KAM_STOCKTIP101,[l=0]# => q#/WDSC/i#,
  q#__KAM_STOCKTIP102,[l=1]# => q#/(Distributed Power|DPWI)/is#,
  q#__KAM_STOCKTIP103,[l=1]# => q#/(HUMET-PBC|L9Z\.F)/is#,
  q#__KAM_STOCKTIP104,[l=1]# => q#/ASVP/is#,
  q#__KAM_STOCKTIP105,[l=1]# => q#/CHVC/is#,
  q#__KAM_STOCKTIP106,[l=1]# => q#/(China Datacom|CDPN)/is#,
  q#__KAM_STOCKTIP107,[l=1]# => q#/(ORAMED PHARMA|OJU\.F)/is#,
  q#__KAM_STOCKTIP108,[l=1]# => q#/(DSDI|DSI Direct Sales)/is#,
  q#__KAM_STOCKTIP11,[l=1]# => q#/(?:Gulf Petroleum|GFPE)/is#,
  q#__KAM_STOCKTIP111,[l=1]# => q#/(COMPLIANCE SYSTEMS|(\b|^)COPI(\b|$))/is#,
  q#__KAM_STOCKTIP112,[l=1]# => q#/(Global Pay Solutions|(\b|^)GPSI(\b|$))/is#,
  q#__KAM_STOCKTIP113,[l=0]# => q#/(MEGOLA|MGOA)/i#,
  q#__KAM_STOCKTIP114,[l=1]# => q#/(\b|^)ADOV(\b|$)/i#,
  q#__KAM_STOCKTIP115,[l=1]# => q#/(Oncology Med|(\b|^)ONCO(\b|$))/is#,
  q#__KAM_STOCKTIP116,[l=1]# => q#/(Strategy X|SGXI)/is#,
  q#__KAM_STOCKTIP117,[l=1]# => q#/(Spotlight Homes|COST CONTAINMENT TEC|SPHM)/is#,
  q#__KAM_STOCKTIP118,[l=1]# => q#/((\b|^)SREA(\b|$)|Score One)/is#,
  q#__KAM_STOCKTIP119,[l=1]# => q#/(Monster Motors|MRMT)/is#,
  q#__KAM_STOCKTIP12,[l=1]# => q#/(?:Patriot Mechanical Handling|PMHH)/is#,
  q#__KAM_STOCKTIP120,[l=0]# => q#/(EntreMetrix|ERMX)/i#,
  q#__KAM_STOCKTIP121,[l=1]# => q#/(VISION AIRSHIPS|VPSN)/is#,
  q#__KAM_STOCKTIP122,[l=1]# => q#/(Shandong Zhouyuan Seed and Nursery|SZSN)/is#,
  q#__KAM_STOCKTIP124,[l=1]# => q#/(VGPM|Vega Promotional Sys)/is#,
  q#__KAM_STOCKTIP127,[l=1]# => q#/(Physical Property Holdings|(\b|^)PPYH(\b|$))/is#,
  q#__KAM_STOCKTIP128,[l=1]# => q#/(MONUMENTAL MARKETING|(\b|^)MNUM(\b|$))/is#,
  q#__KAM_STOCKTIP129,[l=1]# => q#/(EnerBrite Technologies Group|eTgU)/is#,
  q#__KAM_STOCKTIP13,[l=1]# => q#/(?:KSW Industries|KSWJ)/is#,
  q#__KAM_STOCKTIP130,[l=1]# => q#/(Pricester|PRCC)/is#,
  q#__KAM_STOCKTIP131,[l=1]# => q#/(Greenstone Holdings|GSHN)/is#,
  q#__KAM_STOCKTIP132,[l=1]# => q#/((\b|^)AGMS(\b|$)|Angstrom[- ]Microsystems)/is#,
  q#__KAM_STOCKTIP133,[l=1]# => q#/(Pluris Energy|PEYG)/is#,
  q#__KAM_STOCKTIP134,[l=1]# => q#/(United Consortium|(\b|^)UCSO(\b|$))/is#,
  q#__KAM_STOCKTIP135,[l=1]# => q#/(Dominion Minerals|DMNM)/is#,
  q#__KAM_STOCKTIP136,[l=1]# => q#/(PrimeGen Energy|PGNE)/is#,
  q#__KAM_STOCKTIP137,[l=1]# => q#/Dynamic Response Group|DRGZ/is#,
  q#__KAM_STOCKTIP138,[l=1]# => q#/Cobra Oil (and|&) Gas|CGCA/is#,
  q#__KAM_STOCKTIP139,[l=1]# => q#/Solanex Management|SLNX/is#,
  q#__KAM_STOCKTIP14,[l=1]# => q#/(?:Conforce International|CFRI)/is#,
  q#__KAM_STOCKTIP140,[l=1]# => q#/BIO-SOLUTIONS|BISU/is#,
  q#__KAM_STOCKTIP141,[l=1]# => q#/(\b|^)FORC(\b|$)/is#,
  q#__KAM_STOCKTIP142,[l=1]# => q#/Hawk Systems Inc|HWSYD/is#,
  q#__KAM_STOCKTIP143,[l=1]# => q#/AmeriLithium|(\b|^)AMEL(\b|$)/is#,
  q#__KAM_STOCKTIP144,[l=1]# => q#/Fleet Management Solutions|FLMG/is#,
  q#__KAM_STOCKTIP146,[l=1]# => q#/Plandai|PLPL/is#,
  q#__KAM_STOCKTIP148,[l=0]# => q#/STBV/i#,
  q#__KAM_STOCKTIP149,[l=0]# => q#/LifeApps|LFAP/i#,
  q#__KAM_STOCKTIP15,[l=1]# => q#/(?:Nano Superlattice Technology|NSLT)/is#,
  q#__KAM_STOCKTIP150,[l=0]# => q#/MONARCHY RESOURCES/i#,
  q#__KAM_STOCKTIP151,[l=0]# => q#/Alanco Tech/i#,
  q#__KAM_STOCKTIP152,[l=0]# => q#/Siga Resources/i#,
  q#__KAM_STOCKTIP153,[l=1]# => q#/INSCOR|(\b|^)IOGA(\b|$)/is#,
  q#__KAM_STOCKTIP154,[l=1]# => q#/mLight Tech|(\b|^)MLGT(\b|$)/is#,
  q#__KAM_STOCKTIP155,[l=1]# => q#/Alanco Technologies/is#,
  q#__KAM_STOCKTIP16,[l=1]# => q#/(?:Morgan Beaumont|MBEU)/is#,
  q#__KAM_STOCKTIP17,[l=1]# => q#/(?:Relay Capital|(^|\b)RLYC($|\b))/is#,
  q#__KAM_STOCKTIP18,[l=1]# => q#/(?:Madison Explorations|(?:^|\b)MDEX(?:$|\b))/is#,
  q#__KAM_STOCKTIP2,[l=1]# => q#/(?:KOKO PETROLEUM|KKPT)/is#,
  q#__KAM_STOCKTIP20,[l=1]# => q#/(?:PREMIER INFORMATION|(?:^|\b)PIFR(?:$|\b))/is#,
  q#__KAM_STOCKTIP21,[l=1]# => q#/(?:Harbin Pingchuan|P G C N|PGCN)/is#,
  q#__KAM_STOCKTIP22,[l=1]# => q#/(?:CLIENT TRACK CORP|CTKR)/is#,
  q#__KAM_STOCKTIP23,[l=1]# => q#/(?:EXTREME INNOVATIONS|(^|\b)EXTI($|\b))/is#,
  q#__KAM_STOCKTIP24,[l=1]# => q#/(?:Medical Home Products|MHPT)/is#,
  q#__KAM_STOCKTIP25,[l=1]# => q#/(?:AmeraMex International|AMMX)/is#,
  q#__KAM_STOCKTIP26,[l=1]# => q#/(?:Equipment & Systems Engineering|EQUIPMENT & SYS ENGR|EQSE)/is#,
  q#__KAM_STOCKTIP27,[l=0]# => q#/(?:NANOFORCE|NNFC)/i#,
  q#__KAM_STOCKTIP29,[l=1]# => q#/(?:Innovation Holdings|IVHN)/is#,
  q#__KAM_STOCKTIP3,[l=1]# => q#/(?:DARK DYNAMITE|DKDY|D K D Y)/is#,
  q#__KAM_STOCKTIP30,[l=1]# => q#/(?:GOLDEN APPLE OIL|GAPJ)/is#,
  q#__KAM_STOCKTIP32,[l=1]# => q#/(?:Midland Baring Financial Group|MDBF)/is#,
  q#__KAM_STOCKTIP33,[l=1]# => q#/(?:Aradyme Corporation|A D Y E)/is#,
  q#__KAM_STOCKTIP34,[l=1]# => q#/(?:TRANSAKT CORP|TKTJF)/is#,
  q#__KAM_STOCKTIP35,[l=1]# => q#/(?:CTXE|CANTEX ENERGY CORP)/is#,
  q#__KAM_STOCKTIP36,[l=1]# => q#/(?:De Greko|DGKO)/is#,
  q#__KAM_STOCKTIP37,[l=1]# => q#/(?:Deep Earth Resource, Inc|CTFE|DPER)/is#,
  q#__KAM_STOCKTIP38,[l=1]# => q#/(?:Vemics|VMCI|Summit Financial Resources)/is#,
  q#__KAM_STOCKTIP39,[l=1]# => q#/Premium Petroleum/is#,
  q#__KAM_STOCKTIP4,[l=1]# => q#/(?:Remington Ventures|RMVN)/is#,
  q#__KAM_STOCKTIP41,[l=1]# => q#/(?:CHINA GOLD CORP|CGDC)/is#,
  q#__KAM_STOCKTIP42,[l=0]# => q#/DPEK/i#,
  q#__KAM_STOCKTIP43,[l=1]# => q#/(?:Amerossi International Group|A M S N(\b|$)|AMSN)/is#,
  q#__KAM_STOCKTIP47,[l=1]# => q#/(?:Holly ?wood Intermediate|HYWI|H Y W I)/is#,
  q#__KAM_STOCKTIP5,[l=1]# => q#/(?:m-Wise|MWIS|M W I S)/is#,
  q#__KAM_STOCKTIP50,[l=0]# => q#/(?:COSCO|CCPI)/i#,
  q#__KAM_STOCKTIP52,[l=1]# => q#/(?:KMA Global Solutions International|KMAG)/is#,
  q#__KAM_STOCKTIP53,[l=1]# => q#/(?:Advanced Powerline Technologies|APWL)/is#,
  q#__KAM_STOCKTIP54,[l=1]# => q#/(?:GOLDMARK INDUSTRIES|GDKI)/is#,
  q#__KAM_STOCKTIP55,[l=1]# => q#/(?:QUANTUM ENERGY|QEGY)/is#,
  q#__KAM_STOCKTIP56,[l=1]# => q#/(?:AAGA RESOURCE+S NEW|A G A O|(\b|^)AGAO(\b|$))/is#,
  q#__KAM_STOCKTIP57,[l=1]# => q#/(?:Bicoastal Communications|BCLC|B C L C)/is#,
  q#__KAM_STOCKTIP59,[l=1]# => q#/(?:Viva International|VIVI)/s#,
  q#__KAM_STOCKTIP6,[l=1]# => q#/(?:China World Trade Corporation|CWTD)/is#,
  q#__KAM_STOCKTIP60,[l=1]# => q#/(?:WILON RESOURCES|WLON)/is#,
  q#__KAM_STOCKTIP62,[l=1]# => q#/(?:DEFENSE DIRECTIVE|DFSE)/is#,
  q#__KAM_STOCKTIP63,[l=1]# => q#/(?:Cyberhand Technologies|CYHD)/is#,
  q#__KAM_STOCKTIP64,[l=1]# => q#/(?:Texhoma Energy|TXHE)/is#,
  q#__KAM_STOCKTIP65,[l=1]# => q#/(?:Equal Trading|EQTD)/is#,
  q#__KAM_STOCKTIP68,[l=1]# => q#/(?:X-tra Petroleum|XTPT)/is#,
  q#__KAM_STOCKTIP69,[l=1]# => q#/(?:Red Reef Laboratories|(\b|^)RREF(\b|$))/is#,
  q#__KAM_STOCKTIP7,[l=1]# => q#/(?:Packets International|IPKL)/is#,
  q#__KAM_STOCKTIP70,[l=1]# => q#/(?:Great American Food Chain|GAMN)/is#,
  q#__KAM_STOCKTIP71,[l=1]# => q#/(?:Cana Petroleum|CNPM)/is#,
  q#__KAM_STOCKTIP72,[l=1]# => q#/(?:China Health Management|CNHC)/is#,
  q#__KAM_STOCKTIP73,[l=1]# => q#/(?:Makeup Limited|MAKU)/is#,
  q#__KAM_STOCKTIP74,[l=1]# => q#/(?:Premier Holdings Group|PMHD)/is#,
  q#__KAM_STOCKTIP75,[l=1]# => q#/(?:VSUS technologies|(\b|^)VSUS($|\b))/is#,
  q#__KAM_STOCKTIP76,[l=1]# => q#/(?:FLAIR PETROLEUM|FPMC)/is#,
  q#__KAM_STOCKTIP77,[l=1]# => q#/(?:Physician Adult Daycare|PHYA)/is#,
  q#__KAM_STOCKTIP78,[l=1]# => q#/(?:AlgoDyne Ethanol Energy|(\b|^)ADYN(\b|$))/is#,
  q#__KAM_STOCKTIP79,[l=1]# => q#/(?:Critical Care.{1,3}Inc|CTCX)/is#,
  q#__KAM_STOCKTIP8,[l=1]# => q#/(?:Infinex Ventures|IFNX)/is#,
  q#__KAM_STOCKTIP80,[l=1]# => q#/(?:Aerofoam Metals|AFML)/is#,
  q#__KAM_STOCKTIP81,[l=1]# => q#/(?:Ten \& 10|(?:\b|^)TTEN)/is#,
  q#__KAM_STOCKTIP82,[l=1]# => q#/(?:Medical Institutional Services|MISJ(\b|$))/is#,
  q#__KAM_STOCKTIP83,[l=1]# => q#/(?:Harris Exploration|HXPN)/is#,
  q#__KAM_STOCKTIP84,[l=1]# => q#/(?:MARSHAL HOLDINGS|MHII)/is#,
  q#__KAM_STOCKTIP85,[l=1]# => q#/(?:ADVANCED GROWING SYSTEMS|AGWS)/is#,
  q#__KAM_STOCKTIP86,[l=1]# => q#/(?:WEST EXCELSIOR ENT|WEXE)/is#,
  q#__KAM_STOCKTIP87,[l=1]# => q#/(?:Hemisphere Gold|HPGI)/is#,
  q#__KAM_STOCKTIP88,[l=1]# => q#/(?:Victory Energy Corporation|VYEY)/is#,
  q#__KAM_STOCKTIP89,[l=0]# => q#/UTEV/i#,
  q#__KAM_STOCKTIP9,[l=1]# => q#/(?:FacePrint Global Solutions|FCPG)/is#,
  q#__KAM_STOCKTIP90,[l=1]# => q#/(?:CHINA BIOLIFE ENTERP|CBFE)/is#,
  q#__KAM_STOCKTIP92,[l=0]# => q#/CBRJ/i#,
  q#__KAM_STOCKTIP93,[l=1]# => q#/(?:LAS VEGAS CENTRAL RESERVATIONS|LVCC)/is#,
  q#__KAM_STOCKTIP94,[l=0]# => q#/GTAP/i#,
  q#__KAM_STOCKTIP98,[l=0]# => q#/PLMA/i#,
  q#__KAM_STOCKTIP99,[l=0]# => q#/CDYV/i#,
  q#__KAM_SURVEY3,[l=0]# => q#/Do You Use Instagram|Complete the survey/i#,
  q#__KAM_SWIPE3,[l=1]# => q#/pennies on the dollar|join, bid|penny auctions|\d% .{0,10}retail|ipads on auction|bid now|factory sealed ipads|cheap ipads|for pennies|ebay killer|Inventory Clearance on iPads|crazy auctions|XPS for \d\dUSD|iphone.{1,10}clearance/i#,
  q#__KAM_SWIPE4,[l=0]# => q#/SwipeBids|Swipe Auction|CIRCLE MEDIA BIDS|Wavee|BIGGER BIDDER|Bidooka|Sellmoo|overstocked auctions|for pennies/i#,
  q#__KAM_TAX3,[l=0]# => q#/File your taxes for free|need more time/i#,
  q#__KAM_TELEWORK1,[l=1]# => q#/(generate|make) .{0,10}1.5K? (to|-) 3.5K (a day|daily|per day|per month)|makes? \$[\d,]+\/month|upgrade your salary/is#,
  q#__KAM_TELEWORK2,[l=1]# => q#/have a (?:tele)?phone|money making challenge|has full internet/is#,
  q#__KAM_TELEWORK3,[l=1]# => q#/return(?:ing)? (phone )?calls|working a few hours each day/is#,
  q#__KAM_TELEWORK4,[l=1]# => q#/fully qualified|no experience needed|all the training/is#,
  q#__KAM_TELEWORK5,[l=1]# => q#/work (?:online )?from home|process(?:ing)? rebates (?:at|from) home|set your own hours|100% no risk|Western Union fees|new job or career/is#,
  q#__KAM_TELEWORK6,[l=1]# => q#/earning up to \d+USD|earn thousands of dollars|\d% commission|get rich quick/is#,
  q#__KAM_TESTOSTERONE3,[l=0]# => q#/Boost your testosterone/i#,
  q#__KAM_TESTOSTERONE4,[l=0]# => q#/Testoril/i#,
  q#__KAM_THIRD,[l=1]# => q#/advertisement.{0,12}sent by a third-?party/i#,
  q#__KAM_TIME2,[l=1]# => q#/(replica|diamond|designer[-_ ](piece|collections|watch)|time[-_ ]piece|wrist|time-keeper|\/\/atch)/is#,
  q#__KAM_TIME4,[l=0]# => q#/time|watch/i#,
  q#__KAM_TIME5,[l=0]# => q#/(funny|low) price/i#,
  q#__KAM_TIME6,[l=0]# => q#/(Cx?ARTIER|Bx?REITLING|Px?ATEK|Rx?OLEX|Bx?VLGARI|Tx?IFFANY)/i#,
  q#__KAM_TIMESHARE1,[l=1]# => q#/Get[- ]Cash for Your Timeshare|not using your timeshare|(unwanted|ugly) timeshare|cash out quickly/is#,
  q#__KAM_TIMESHARE2,[l=1]# => q#/goldmine|sell or rent it|we pay cash|sell\/rent your time|own a timeshare or condo/is#,
  q#__KAM_TINNI1,[l=0]# => q#/TinniFix/i#,
  q#__KAM_TINNI2,[l=0]# => q#/Stop the ringing in your ears/i#,
  q#__KAM_TIP3,[l=0]# => q#/undereye bags/i#,
  q#__KAM_TIP4,[l=0]# => q#/Find Out This Quick New Trick/i#,
  q#__KAM_TIRES3,[l=0]# => q#/savings on tire|new tires/i#,
  q#__KAM_TRIAL,[l=1]# => q#/RISK-FREE Trial|Free \d+ day trial|try it free/i#,
  q#__KAM_TUB3,[l=1]# => q#/Walk.?in hot.?tub|bath and massage|easy transfer from a wheelchair/i#,
  q#__KAM_TV1,[l=0]# => q#/watch unlimited television|DTV4PC|Online TV Code|Free DVD-CD Burner|100% legal|Rabbit TV/i#,
  q#__KAM_TV2,[l=0]# => q#/without a monthly fee|pay a cable or satellite bill|no monthly fee|watch uncensored|movies online|no censorship/i#,
  q#__KAM_UNIV1,[l=1]# => q#/(University Administration|University Enrollment|Education Assessment|Faculty Assessment|University Degree|Administration Office|Education office|Schools office|Enrollment Office|Online University)/is#,
  q#__KAM_UNIV11,[l=1]# => q#/(degree|transcript) in any field|Field of yourr? ch[oò][iì]ce/is#,
  q#__KAM_UNIV12,[l=1]# => q#/(obtain your diploma|diploma that you want|Criminal Justice or Homeland Security degree)/is#,
  q#__KAM_UNIV13,[l=1]# => q#/(degree|field|diploma) of your (choice|expertise)/is#,
  q#__KAM_UNIV14,[l=1]# => q#/(earn a|full) transcript/is#,
  q#__KAM_UNIV15,[l=1]# => q#/(No Study Required|Without Exams|No (examinations|[eÉ]xams)|without attending a single class|no classes|no textbooks|no (?:required )?tests|degree .{0,30}you deserve)/is#,
  q#__KAM_UNIV16,[l=1]# => q#/\d weeks.{0,30}graduated/is#,
  q#__KAM_UNIV18,[l=1]# => q#/100% discrete/is#,
  q#__KAM_UNIV1B,[l=1]# => q#/\d (months|weeks)/i#,
  q#__KAM_UNIV2,[l=1]# => q#/\d (week|month).{0,30}degree/is#,
  q#__KAM_UNIV3,[l=1]# => q#/(past work|professional|based on your|earned from|life|life and work|present work) experience/is#,
  q#__KAM_UNIV3B,[l=1]# => q#/(dead end job|improve your future, and your income|high paying jobs|bec[óo]me a do[cç]tor|get your diploma today)/is#,
  q#__KAM_UNIV4,[l=1]# => q#/not official degree|non[ -]?accredited/is#,
  q#__KAM_UNIV4B,[l=1]# => q#/1.?0.?0.?% (legit|verifiable|online|no pre|non[- ]?accredited)/is#,
  q#__KAM_UNIV5,[l=1]# => q#/novelty (degree|use)/is#,
  q#__KAM_UNIV5B,[l=1]# => q#/F A S T[ ]{0,4}T R A C K/is#,
  q#__KAM_UNIV6,[l=1]# => q#/verifiable University Degree/is#,
  q#__KAM_UNIV6B,[l=1]# => q#/DIP\sLOMA/#,
  q#__KAM_UNIV7,[l=1]# => q#/(life|work) experience (diploma|degree|transcript)/is#,
  q#__KAM_UNIV8,[l=1]# => q#/Career Path/is#,
  q#__KAM_UNIV9,[l=1]# => q#/non[- ]?ac(creditee?d)?.{1,10}universit/is#,
  q#__KAM_UNSUB1,[l=0]# => q#/cancel 0ffers/i#,
  q#__KAM_UPS3,[l=0]# => q#/invoice copy attached/i#,
  q#__KAM_URONLINE1,[l=1]# => q#/(chat|chat with me|hook ?up) on Y ?A ?H ?O ?O (tonight|or MSN)|add me with yahoo or msn|view now|press this web link|send me your? photo|can u turn me on|kissing you/i#,
  q#__KAM_URONLINE2,[l=1]# => q#/wanna talk|ur info|found your mail|found ur profile|mutual friend|katya from russia|you came to russia|my gentle sun|see this page I made|match making heaven|meet that special|comee see it over here|hexten.net|looking for a man|waiting for ur mail|found ur account|waiting for your message/i#,
  q#__KAM_URONLINE3,[l=1]# => q#/get (naked|naughty)|horny|naughty toys|I will do anything|TOTALLY msg me on MSN|tell me your mobile|I remember you|let's talk|ran across someone like u|sexywebdating|chatting with someone|saw you by BJs|private e-?mail|dating portal/i#,
  q#__KAM_URUNIT1,[l=1]# => q#/\bur (unit|liveliness|energy level|endurance level)/is#,
  q#__KAM_URUNIT2,[l=1]# => q#/\bur (gf|girl|wife|size|thing|partner|significant other)/is#,
  q#__KAM_URUNIT3,[l=1]# => q#/(unsatisfied|not satisfied|nagging|complaining|complaints|complained|unlimited prowess|increase your volume)/is#,
  q#__KAM_URUNIT3A,[l=1]# => q#/\b(exasperated|fatigued|drained|tired) all the time/is#,
  q#__KAM_URUNIT4,[l=1]# => q#/(bedroom|the bed|nighttime activit|male power|show your girl)/is#,
  q#__KAM_URUNIT5,[l=1]# => q#/(size of (there|their|your) .{0,11}(unit|thing)|using them for a couple months|enhancing formula)/is#,
  q#__KAM_URUNIT6,[l=1]# => q#/(majority of women|shrinking .{0,12} baby fat|winning guy|huge explosion)/is#,
  q#__KAM_URZEST2,[l=0]# => q#/or still (?:jaded|worn|drained|exasperated) all the time/i#,
  q#__KAM_URZEST3,[l=0]# => q#/(?:(?:wanting|looking|seeking) to get in the gym|(?:dreaming|seeking|hoping) to get (?:into shape|fit))/i#,
  q#__KAM_URZEST4,[l=0]# => q#/(wks it has been|been mos) since we('| ha)ve chatted/i#,
  q#__KAM_URZEST5,[l=0]# => q#/(back into shape|made me healthier after my disease)/i#,
  q#__KAM_USB1,[l=0]# => q#/(debi|deborah brown|Melissa Sylvan)/i#,
  q#__KAM_USB2,[l=0]# => q#/person (that|who) handles the promotions/i#,
  q#__KAM_USB3,[l=1]# => q#/usbsmg.com/i#,
  q#__KAM_VACATION3,[l=0]# => q#/Resorts FOR FREE/i#,
  q#__KAM_VIAGRA4A,[l=1]# => q#/V (. )?A (. )?L (. )?[I\/t] (. )?U (. )?M/i#,
  q#__KAM_VIAGRA4B,[l=1]# => q#/V (. )?[I\/t] (. )?A (. )?G (. )?R (. )?A/i#,
  q#__KAM_VIAGRA7A,[l=1]# => q#/V[ij]+AGRA/i#,
  q#__KAM_VIAGRA7C,[l=1]# => q#/AMB[ij]+EN/i#,
  q#__KAM_VIAGRA7D,[l=1]# => q#/VAL[ij]+UM/i#,
  q#__KAM_VIAGRA8A,[l=1]# => q#/VI...?AGRA/i#,
  q#__KAM_VIAGRA8B,[l=1]# => q#/AM...?BIEN/i#,
  q#__KAM_VIAGRA8C,[l=1]# => q#/VA...?LIUM/i#,
  q#__KAM_VIAGRA8D,[l=1]# => q#/CI...?ALIS/i#,
  q#__KAM_VIAGRA9A,[l=1]# => q#/V[IL1]A..GRA/i#,
  q#__KAM_VIAGRA9B,[l=1]# => q#/AMB..IEN/i#,
  q#__KAM_VIAGRA9C,[l=1]# => q#/VAL..IUM/i#,
  q#__KAM_VIAGRA9D,[l=1]# => q#/C[IL1]A..LIS/i#,
  q#__KAM_WARRANTY2,[l=0]# => q#/Protect your home|choice home warranty|unexpected repair/i#,
  q#__KAM_WARRANTY3,[l=0]# => q#/home warrant|complimentary insurance quote/i#,
  q#__KAM_WEALTH2,[l=1]# => q#/www.(wealthmax|bizrlr).co.cc/i#,
  q#__KAM_WEALTH3,[l=0]# => q#/Wealth Builder/i#,
  q#__KAM_WEB2,[l=0]# => q#/INDIA based IT/i#,
  q#__KAM_WEB3,[l=0]# => q#/Online Marketing Consultant/i#,
  q#__KAM_WEIGHT1,[l=1]# => q#/(overweight|extra weight|glutting|shed fat|burns fat|burn calories|appetite suppressant|stimulate your metabolism|unwanted weight|duet of the year|healthy energy boost|Suppresses Appetite|internal cleansing|detoxify|cellulite|unsightly bulges|fat burn|Diet of the year|acai|cuts cholesterol|cleanse excess waste|free sample|unwanted weight|Acai suppl[ie]ments|Diet\/Detox|[hash]1 Weight Loss|lose body fat|lose \d+\s*lbs in just|calorie burning machine|before eating carbs)/is#,
  q#__KAM_WEIGHT2,[l=1]# => q#/(\d pounds|lose[_ ]weight|suppress appetite|appetite out of control|Oprah|for cancer patients|colon cure|colon cleanse|colonmate|avai berry|acai burn|ultraslim|feel energized|excess[_ ]weight|no diet changes|no exercise|hollywood'?s hottest -?diet|acai berry edge|Acai Diet|top secret diet|Power HCG|Sensa|shocking method|Jennifer Aniston|before eating carbs|all natural weight.?loss|green fruit|top celeb's diet)/is#,
  q#__KAM_WHATS3,[l=1]# => q#/WhatsApp/#,
  q#__KAM_WHITEN2,[l=0]# => q#/whitener/i#,
  q#__KAM_WHITEN3,[l=0]# => q#/(Celebrity Smile|Carbamide Peroxide)/i#,
  q#__KAM_WIFE2,[l=1]# => q#/marry a Russian|sizzling photos|meet russian (women|beauties)|Russian ?bride|Slavic babes/i#,
  q#__KAM_WINDOWS3,[l=0]# => q#/Find Your Windows/i#,
  q#__KAM_WORKHOME1,[l=0]# => q#/online jobs|Full-time (and|&) Part-time|at home employment/i#,
  q#__KAM_WORKHOME2,[l=0]# => q#/[hash]1 site|view here|information here/i#,
  q#__KAM_WTA2,[l=1]# => q#/Alliance for Retirement Prosperity Association|Social Security Institute/is#,
  q#__LARGE_PERCENT_AFTER,[l=1]# => q#/\d{3}% after/i#,
  q#__LOTSA_MONEY_05,[l=1]# => q#/(?:(?:sum|value|amount)\sof\s)[1-9][\d.,\sO]{7,20}[\dO\.][\)\]\(\s]{0,3}(?:pounds?|dollars?|euros?|bucks)\b/i#,
  q#__LOTTO_ADMITS_2,[l=1]# => q#/\b(?:free)?(?:lot(?:to|tery|erie)|sweepstakes)\s(?:(?:inter)?na[tz]ional|department|bureau|group|award|microsoft)/i#,
  q#__LOTTO_AGENT_02,[l=1]# => q#/\blot+ery[^\.]{1,40} ticket agent/i#,
  q#__LOTTO_DEPT,[l=1]# => q#/\b(?:claim(?:s|ing)?(?:\sprocessing)?|fiducia\w+|reimbursement|(?:international|foreign|win+ing)(?:\s(?:rem+it+ance|settlement|payment|award))+|payment|award|compensation|lot+ery)(?:\s\w+)?\s?(?:department|dept|unit|group|committee|bureau)/i#,
  q#__LOTTO_VERIFY,[l=1]# => q#/\bpromo\sverification/i#,
  q#__LOTTO_WIN_01,[l=1]# => q#/\bwin+ing\s(?:prize|number|notification|draw|check|cheque|details|information|payment)/i#,
  q#__LUCKY_WINNER,[l=1]# => q#/\b(?:lucky|gl.cklich(?:en)?|afortunados)\s(?:(?:ge)?win+ers?|ganador(?:es)?|individuals?)\b/i#,
  q#__LUCRATIVE,[l=1]# => q#/\b(?:lucrative|profitable|tr[\xe8]s\ssalutaire)\b/i#,
  q#__MAILBOX_FULL_SE,[l=1]# => q#/(?:\b=F6|[\xf6]|[\xc3][\xb6])verskridit gr(?:=E4|[\xe4]|[\xc3][\xa4])nsen f(?:=F6|[\xf6]|[\xc3][\xb6])r din postl(?:=E5|[\xe5]|[\xc3][\xa5])da\b/i#,
  q#__MAIL_ACCT_ACCESS1,[l=1]# => q#/\b(?:your (?:web ?|e-?)?mail (?:account|log-?in) (?:has )?been accessed|r(?:=F3|[\xf3])zne komputery zalogowaniu sie)\b/i#,
  q#__MAIL_ACCT_ACCESS2,[l=1]# => q#/\blo+se ac+es+ to your (?:web|e-?)?mail (?:account|log-?in|box|address)\b/i#,
  q#__MILLIONS,[l=1]# => q#/\bmillions\sof\s(?:dollar|euro|pound)/i#,
  q#__MY_FORTUNE,[l=1]# => q#/\b(?:my|his|her)\s(?:fortune|heritage)\b/i#,
  q#__NEXT_OF_KIN,[l=1]# => q#/\bnext[-\s]of[-\s]kin\b/i#,
  q#__NIGERIA,[l=1]# => q#/\bnigeria\b/i#,
  q#__NOT_DEAD_YET,[l=1]# => q#/\b(?:will\sinherit|que\sherede)\b/i#,
  q#__NOT_SCAM,[l=1]# => q#/\b(?:not\sa\sscam|(?:not|never)\sscam\syou)\b/i#,
  q#__OUR_BEHALF,[l=1]# => q#/\b(?:on\s(?:my|our)\sbehalf|of\sbehalf\sof)\b/i#,
  q#__PAY_YOU,[l=1]# => q#/\bpay\syou\b/#,
  q#__PILL_PRICE_01,[l=1]# => q#m;(?=[\d .f])(?:free|[\d .]{3}(?:/|per|each)) ?(?=[ptc])(?:pill|tablet|cap(?:sule|let))s?\b;i#,
  q#__PILL_PRICE_02,[l=1]# => q#/(?=[ptc])(?:pill|tablet|cap(?:sule|let))s[-= :]{1,5}\$?[\d .]{3}/i#,
  q#__PLS_REVIEW,[l=1]# => q#/\b(?:please|kindly)\s(?:(?:re)?view|see)(?:\s\w+)?\sattach(?:ed|ment)\b/i#,
  q#__PUMPDUMP_01,[l=1]# => q#/\b(?:times|multiply|tripl(?:e|ing)|quadrupl(?:e|ing)|quintupl(?:e|ing)) (?:your|an) (?:princip(?:al|le)|investment)\b/i#,
  q#__PUMPDUMP_03,[l=1]# => q#/\bbuy (?:[^.!]{1,30} )?(?:(?:(?:mon|tues|wednes|thurs|fri)day|tomorrow) (?:first thing|open|morning)|(?:first thing|opens|before) (?:(?:mon|tues|wednes|thurs|fri)day|tomorrow))/i#,
  q#__PUMPDUMP_04,[l=1]# => q#/\bmake you (?:big bucks|hundreds|thousands)\b/i#,
  q#__PUMPDUMP_06,[l=1]# => q#/\brecommend(?:ed|s)? (?:a|this) (?:company|stock)\b/i#,
  q#__PUMPDUMP_07,[l=1]# => q#/\b(?:buy|grab it) for (?:around |about |less than )?\d+ cents\b/i#,
  q#__PUMPDUMP_09,[l=1]# => q#/\b(?:buy|get|snap up|grab) as many shares (?:of it )?as (?:you|I) can\b/i#,
  q#__PUMPDUMP_10,[l=1]# => q#/\btrading at (?:such )?a (?:bargain|cheap|low)\b/i#,
  q#__RANDOM_PICK,[l=1]# => q#/\b(?:random(?:ly)?\s(?:\w+\s)?(?:select(?:ion|ed)|pick(?:ed)?|computer)|(?:select|pick)ed\s(?:at\s)?random(?:ly)?|(?:esco(?:g|lh)idos|seleccion) (?:aleatoria(?:mente)?|al azar))\b/i#,
  q#__RUDE_HTML_1,[l=0]# => q#/Get a capable html e-mailer/i#,
  q#__RUDE_HTML_2,[l=1]# => q#/not support the display of HTML. Please view this message in a different/i#,
  q#__RUDE_HTML_3,[l=0]# => q#/This message contains an HTML formatted message but your email client does/i#,
  q#__RUDE_HTML_4,[l=1]# => q#/Your mailer do not support HTML messages. Switch to a better mailer/i#,
  q#__SCAM,[l=1]# => q#/\bscam(?:m?e[dr])?s?\b/i#,
  q#__SECURITY_DEPT,[l=1]# => q#/\bsecurity dep(?:artmen)?t\b/i#,
  q#__STOCK_TIP,[l=1]# => q#/\bsto[ck]{2}\s?tip\b/i#,
  q#__STYLE_TAG_IN_BODY,[l=1]# => q#/<style(?:[^>]{0,30})?>/i#,
  q#__SUBSCRIPTION_INFO,[l=1]# => q#/\b(?:e?newsletters?|(?:un)?(?:subscrib|register)|you(?:r| are) subscri(?:b|ption)|opt(?:.|ing)?out\b|further info|you do ?n[o']t w(?:ish|ant)|remov\w{1,3}.{1,9}\blists?\b|to your white.?list)/i#,
  q#__SUM_OF_FUND,[l=1]# => q#/\b(?:sum|release|freigabe)\s(?:of|der)\s(?:amount|fund|investment|mittel)\b/i#,
  q#__SURVEY,[l=1]# => q#/\bsurvey\b/i#,
  q#__SYSADMIN,[l=1]# => q#/\b(?:help?[- ]?desk|(?:(?:web ?)?mail ?|sys(?:tem )?)admin(?:istrator)|local[- ]host|(?:support|upgrade|management) (?:team|center)|message from administrator|university mail server copyright|suporte t(?:=E9|[\xe9]|[\xc3][\xa9])cnico|administrador do sistema)\b/i#,
  q#__THEY_INHERIT,[l=1]# => q#/\b(?:inherit\sth(?:e|is)\smoney|herede\sest[ea]\sdinero)\b/i#,
  q#__THIS_AD,[l=1]# => q#/(?:\b|_)this[- _]+(?:ad(?:vert[i1l]sement)?|promo(?:tion)?)s?(?:\b|_)/i#,
  q#__TO_YOUR_ORG,[l=1]# => q#/\b(?:to|for) your organi[sz]ation\b/i#,
  q#__TRAVEL_AGENT,[l=1]# => q#/\btravel\sagen(?:t|cy)\b/i#,
  q#__TRAVEL_BUSINESS,[l=1]# => q#/\bbusiness\stravel\b/i#,
  q#__TRAVEL_ITINERARY,[l=0]# => q#/(?:travel|ticketed|your|current) itinerary/i#,
  q#__TRAVEL_PROFILE,[l=1]# => q#/\btravel+er\sprofile\b/i#,
  q#__TRAVEL_RESERV,[l=1]# => q#/\b(?:reservation\s(?:confirmed|number)|travel\sreservations?)\b/i#,
  q#__TRTMT_DEFILED,[l=1]# => q#/\bdefiled\sall\s(?:forms\sof\s)?(?:medical\s)?treatments?\b/i#,
  q#__TRUNK_BOX,[l=1]# => q#/\b(?:(?:trunk|metallic|proof|security|consignment)\sbox(?:es)?|sealed\ssafe|une mallette m(?:e|=E9|[\xe9]|[\xc3][\xa9])tallique)\b/i#,
  q#__TRUSTED_CHECK,[l=1]# => q#/\b(?:cashier'?s?|certified)\sche(?:ck|que)/i#,
  q#__TVD_PH_BODY_01,[l=1]# => q#/\baccount .{0,20}placed? [io]n restricted status/i#,
  q#__TVD_PH_BODY_02,[l=1]# => q#/\brecords (?:[a-z_,-]+ )+?(?:feature|(?:a|re)ward)/i#,
  q#__TVD_PH_BODY_03,[l=1]# => q#/\byou(?:'ve| have) been (?:[a-z_,-]+ )+?payment/i#,
  q#__TVD_PH_BODY_04,[l=1]# => q#/\bfunds? (?!transfer from)(?!from)(?!in)(?!via)(?:[a-z_,-]+ )+?to your (?:[a-z_,-]+ )*?account/i#,
  q#__TVD_PH_BODY_05,[l=1]# => q#/\bthis is (?:[a-z_,-]+ )+?protect (?:[a-z_,-]+ )+?your/i#,
  q#__TVD_PH_BODY_06,[l=1]# => q#/Dear [a-z]+ bank (?:member|customer)/i#,
  q#__TVD_PH_BODY_07,[l=1]# => q#/\bguarantee the safety of your (?:[a-z_,-]+ )*?account/i#,
  q#__TVD_PH_BODY_08,[l=1]# => q#/\bmultiple password failures/i#,
  q#__TVD_PH_BODY_ACCOUNTS_POST,[l=1]# => q#/\b(?:(?:[dr]e-?)?activat[a-z]*|(?:re-?)?validate|secure|restore|confirm|update|suspend) (?!your)(?:[a-z_,-]+ )+?accounts?\b/i#,
  q#__TVD_PH_BODY_ACCOUNTS_PRE,[l=1]# => q#/\baccounts? (?:[a-z_,-]+ )+?(?:record[a-z]*|suspen[a-z]+|notif(?:y|ication)|updated|verifications?|credited)\b/i#,
  q#__UN,[l=1]# => q#/\bunited\snations?\b/i#,
  q#__VALIDATE_MBOX_SE,[l=1]# => q#/(?:\b=E5|[\xe5]|[\xc3][\xa5])terst(?:=E4|\xe4|[\xc3][\xa4])lla ditt konto\b/i#,
  q#__VBOUNCE_AMAVISD2,[l=1]# => q#/\bV I R U S\b/#,
  q#__VBOUNCE_AOL,[l=1]# => q#/TRANSACTION FAILED - Unrepairable Virus Detected. /#,
  q#__VBOUNCE_ATTACHMENT0,[l=1]# => q#/(?:Attachment.{0,40}was Deleted|the infected attachment)/#,
  q#__VBOUNCE_ATT_QUAR,[l=1]# => q#/\bThe attachment was quarantined\b/#,
  q#__VBOUNCE_AVREPORT0,[l=0]# => q#/(antivirus system report|the antivirus module has|illegal attachment|Unrepairable Virus Detected)/i#,
  q#__VBOUNCE_CLICKBANK,[l=1]# => q#/\bvirus scanner deleted your message\b/i#,
  q#__VBOUNCE_DUTCH,[l=1]# => q#/bevatte bijlage besmet welke besmet was met een virus/#,
  q#__VBOUNCE_EXIM,[l=1]# => q#/a potentially executable attachment /#,
  q#__VBOUNCE_GUIN,[l=1]# => q#/message contains file attachments that are not permitted/#,
  q#__VBOUNCE_MAILMARSHAL,[l=1]# => q#/Mail.?Marshal Rule: Inbound Messages : Block Dangerous Attachments/#,
  q#__VBOUNCE_MAILSWEEP,[l=1]# => q#/MAILsweeper has found that a \S+ \S+ \S+ \S+ one or more virus/#,
  q#__VBOUNCE_MAILSWEEP2,[l=1]# => q#/\bblocked by Mailsweeper\b/i#,
  q#__VBOUNCE_QUOTED_EXE,[l=1]# => q#/> TVqQAAMAAAAEAAAA/#,
  q#__VBOUNCE_REJ_FILT,[l=1]# => q#/Reason: Rejected by filter/#,
  q#__VBOUNCE_SECURIQ,[l=1]# => q#/\bGROUP securiQ.Wall\b/#,
  q#__VBOUNCE_SMTP,[l=1]# => q#/host \S+ said: 5\d\d\s+Error: Message content rejected/#,
  q#__VBOUNCE_STRIP_ATTACH,[l=1]# => q#/\bhas stripped one or more attachments from the following message\b/#,
  q#__VBOUNCE_VALERT,[l=1]# => q#/The mail message \S+ \S+ you sent to \S+ contains the virus/#,
  q#__WEBMAIL_ACCT,[l=1]# => q#/\byour web ?mail account/i#,
  q#__WIDOW,[l=1]# => q#/\b(?:widow(?:e[rd])'?s?|veuve)\b/i#,
  q#__WILL_LEGAL,[l=1]# => q#/\b(?:codicil|last\stestament|probate|executor|intestate|bequest|mandamus)\b/i#,
  q#__WIRE_XFR,[l=1]# => q#/\b(?:wire|telegraph(?:ic)?|bank)\s?transfer/i#,
  q#__YOUR_BANK,[l=1]# => q#/\byour?\s(?:full\s)?bank(?:ing)?\sinformations?\b/i#,
  q#__YOUR_FUND,[l=1]# => q#/\b(?:your|ihr)\s(?:unpaid\s|win+ing\s|ap+roved\s|foreign\s|overdue\s|outstanding\s|contract\s|inheritance\s|nicht\sausbezahlten\s){0,3}(?:fund|payment|geld)\b/i#,
  q#__YOUR_PERM,[l=1]# => q#/\byour\spermission\b/i#,
  q#__YOUR_PROFIT,[l=1]# => q#/\byour?\sprofit/i#,
  q#__YOU_ASSIST,[l=1]# => q#/\b(?:your\sas+istan(?:ce|t)|votre\s(?:as+istance|aide))\b/i#,
  q#__YOU_INHERIT,[l=1]# => q#/\byour\s[a-z\s]{0,30}inherit+ance\b/i#,
  q#__YOU_WON_01,[l=1]# => q#/\byou(?:r|'re|'ve|'ll|\shave|\sdid)?\s(?:e-?mail\s)?(?:\w+\s){0,2}(?:a\s)?w[io]n+(?:er|ing)?(?!'t)\b/i#,
  q#__YOU_WON_02,[l=1]# => q#/\bw[io]n\s(?:(?:for|by)\s)?your?\b/i#,
  q#__YOU_WON_04,[l=1]# => q#/\bqu[ei]\s?(?:vous (?:[\xc3][\xaa]|=C3=AA|[\xea]|e)tes\s?gagnant|en\scons(?:e|=E9|[\xe9]|[\xc3][\xa9])quence\sgagne)\b/i#,
  q#__YOU_WON_05,[l=1]# => q#/\bI won\b/i#,
  q#__freemail_safe_fwd,[l=1]# => q#/---\s?(?:(?:Forwarded|Original) message|Alkuper.inen viesti)/i#,

};

XSLoader::load 'Mail::SpamAssassin::CompiledRegexps::body_0', $VERSION;
}

1;
__END__

=head1 NAME

Mail::SpamAssassin::CompiledRegexps::body_0 - Efficient string matching for regexps found in bases_body_0.in

=head1 SYNOPSIS

  use Mail::SpamAssassin::CompiledRegexps::body_0;
  
  ...
  my $match = Mail::SpamAssassin::CompiledRegexps::body_0::scan($string);

=head1 DESCRIPTION

This module was created by SpamAssassin with the aid of re2xs, which uses re2c
to create an XS library capable of scanning through a bunch of regular
expressions as defined in F<bases_body_0.in>.

See C<sa-compile> for more details.

=cut
