#!/bin/sh
set -e
# Automatically added by dh_installsystemd/12.1.1
if [ -d /run/systemd/system ] && [ "$1" = remove ]; then
	deb-systemd-invoke stop 'clamav-unofficial-sigs.service' 'clamav-unofficial-sigs.timer' >/dev/null || true
fi
# End automatically added section
